/-
Grammar compression, and the exercise `exer:polyregular-marked-squaring-compression`
of the chapter *Polyregular functions* (`polyregular-intro.tex`) of *Transducers*
(M. Bojańczyk).

Exercise `exer:rational-compression` defines a *grammar compression* of a string
to be a context-free grammar that generates that string and nothing else, and
calls a function *compatible with compression* when a compression of the output
can be computed in polynomial time from a compression of the input.  Polynomial
time is not part of this formalisation, so what is proved here is the stronger,
purely combinatorial statement that the author's solution actually establishes:
already the *size* of every compression of the output of marked squaring is
exponential in the size of a compression of the input, so no algorithm at all —
in particular no polynomial-time one — can produce it.

A grammar that generates exactly one string is taken in the standard binary
(straight-line program) form: a list of rules, the `i`-th of which is either a
single letter or the concatenation of the values of two *earlier* rules, and the
string generated is the value of the last rule.  The size of the compression is
the number of rules.  This is the form the author's solution argues about — his
proof considers the rules `X → Y Z` — and every context-free grammar generating
a single string can be brought into it with a linear blow-up.

The combinatorial heart of the solution is the claim that, for a string over a
two-letter alphabet whose letters are called *marked* and *unmarked* here,

  { i | the string has an infix consisting of a marked letter, then `i` unmarked
        letters, then a marked letter }

has at most as many elements as the compression has rules, because each rule
contributes at most one new value.  The marked square of `aᴺ` realises all the
values `1, …, N-1`, whereas `aᴺ` with `N = 2ⁿ` has a compression with `n+1`
rules.
-/
import RequestProject.PartD.MarkedSquare

namespace Transducers
namespace Exercises

/-! ## Grammar compression -/

/-- A rule of a grammar compression: either a single letter, or the
concatenation of the values of two earlier rules. -/
inductive Rule (A : Type) : Type
  /-- A rule `X → a`. -/
  | letter : A → Rule A
  /-- A rule `X → Y Z`, where `Y` and `Z` are the rules with the given
  indices. -/
  | cat : ℕ → ℕ → Rule A

variable {A : Type}

/-- The string generated by the `i`-th rule of a grammar compression.  A rule
`X → Y Z` whose right-hand side does not consist of earlier rules generates the
empty string; such a compression is ill-formed, and the statements below do not
depend on the convention. -/
def slpVal (rs : List (Rule A)) (i : ℕ) : List A :=
  match rs[i]? with
  | none => []
  | some (Rule.letter a) => [a]
  | some (Rule.cat j k) =>
      if hjk : j < i ∧ k < i then slpVal rs j ++ slpVal rs k else []
termination_by i
decreasing_by
  · exact hjk.1
  · exact hjk.2

/-- A grammar compression *generates* a string when the string is the value of
its last rule. -/
def Generates (rs : List (Rule A)) (w : List A) : Prop :=
  rs ≠ [] ∧ slpVal rs (rs.length - 1) = w

lemma slpVal_letter {rs : List (Rule A)} {i : ℕ} {a : A} (h : rs[i]? = some (Rule.letter a)) :
    slpVal rs i = [a] := by
  rw [slpVal, h]

lemma slpVal_cat {rs : List (Rule A)} {i j k : ℕ} (h : rs[i]? = some (Rule.cat j k))
    (hj : j < i) (hk : k < i) : slpVal rs i = slpVal rs j ++ slpVal rs k := by
  rw [slpVal, h]
  simp [hj, hk]

/-! ## The distances between consecutive marked letters -/

/-- The position `p` of `w` carries a marked letter. -/
def markedAt (P : A → Prop) (w : List A) (p : ℕ) : Prop := ∃ x, w[p]? = some x ∧ P x

lemma markedAt_lt {P : A → Prop} {w : List A} {p : ℕ} (h : markedAt P w p) : p < w.length := by
  obtain ⟨x, hx, _⟩ := h
  by_contra hc
  rw [List.getElem?_eq_none (by omega)] at hx
  exact absurd hx (by simp)

/-- The set of numbers `i` such that `w` has an infix consisting of a marked
letter, then `i` unmarked letters, then a marked letter. -/
def gaps (P : A → Prop) (w : List A) : Set ℕ :=
  {i | ∃ p q, p < q ∧ markedAt P w p ∧ markedAt P w q ∧
    (∀ r, p < r → r < q → ¬ markedAt P w r) ∧ i = q - p - 1}

/-- A witnessing infix puts its length into `gaps`. -/
lemma mem_gaps_of_infix (P : A → Prop) {w u z v : List A} {x y : A}
    (hw : w = u ++ x :: (z ++ y :: v)) (hx : P x) (hy : P y) (hz : ∀ c ∈ z, ¬ P c) :
    z.length ∈ gaps P w := by
  subst hw
  set L := u.length with hL
  have hgetx : (u ++ x :: (z ++ y :: v))[L]? = some x := by
    rw [List.getElem?_append_right (by omega)]
    simp [hL]
  have hgety : (u ++ x :: (z ++ y :: v))[L + 1 + z.length]? = some y := by
    rw [List.getElem?_append_right (by omega)]
    have : L + 1 + z.length - L = z.length + 1 := by omega
    rw [this]
    simp
  refine ⟨L, L + 1 + z.length, by omega, ⟨x, hgetx, hx⟩, ⟨y, hgety, hy⟩, ?_, by omega⟩
  intro r hr1 hr2 ⟨c, hc, hPc⟩
  rw [List.getElem?_append_right (by omega)] at hc
  have hr : r - L = (r - L - 1) + 1 := by omega
  rw [hr] at hc
  rw [List.getElem?_cons_succ, List.getElem?_append_left (by omega)] at hc
  exact hz c (List.mem_of_getElem? hc) hPc

/-- Marked positions of a concatenation. -/
lemma markedAt_append (P : A → Prop) (x y : List A) (r : ℕ) :
    markedAt P (x ++ y) r ↔
      (r < x.length ∧ markedAt P x r) ∨ (x.length ≤ r ∧ markedAt P y (r - x.length)) := by
  constructor
  · rintro ⟨c, hc, hPc⟩
    rcases lt_or_ge r x.length with h | h
    · rw [List.getElem?_append_left h] at hc
      exact Or.inl ⟨h, c, hc, hPc⟩
    · rw [List.getElem?_append_right h] at hc
      exact Or.inr ⟨h, c, hc, hPc⟩
  · rintro (⟨h, c, hc, hPc⟩ | ⟨h, c, hc, hPc⟩)
    · exact ⟨c, by rwa [List.getElem?_append_left h], hPc⟩
    · exact ⟨c, by rwa [List.getElem?_append_right h], hPc⟩

/-- A rule `X → Y Z` contributes at most one distance that is not already
contributed by `Y` or by `Z`: the distance of an infix that crosses the boundary
is determined by the two strings. -/
lemma gaps_append (P : A → Prop) (x y : List A) :
    ∃ d, gaps P (x ++ y) ⊆ gaps P x ∪ gaps P y ∪ {d} := by
  classical
  -- a witness that does not cross the boundary lies in one of the two factors
  have hnc : ∀ i ∈ gaps P (x ++ y), ∀ p q : ℕ, p < q → markedAt P (x ++ y) p →
      markedAt P (x ++ y) q → (∀ r, p < r → r < q → ¬ markedAt P (x ++ y) r) →
      i = q - p - 1 → ¬ (p  < x.length ∧ x.length ≤ q) → i ∈ gaps P x ∪ gaps P y := by
    intro i _ p q hpq hp hq hbet hi hcross
    rcases (markedAt_append P x y p).1 hp with ⟨hpL, hpx⟩ | ⟨hpL, hpy⟩
    · -- `p` is in `x`, hence so is `q`
      have hqL : q < x.length := by
        by_contra h
        exact hcross ⟨hpL, by omega⟩
      refine Or.inl ⟨p, q, hpq, hpx, ?_, ?_, hi⟩
      · rcases (markedAt_append P x y q).1 hq with ⟨_, h⟩ | ⟨h, _⟩
        · exact h
        · omega
      · intro r hr1 hr2 hrx
        exact hbet r hr1 hr2 ((markedAt_append P x y r).2 (Or.inl ⟨by omega, hrx⟩))
    · refine Or.inr ⟨p - x.length, q - x.length, by omega, hpy, ?_, ?_, by omega⟩
      · rcases (markedAt_append P x y q).1 hq with ⟨h, _⟩ | ⟨_, h⟩
        · omega
        · exact h
      · intro r hr1 hr2 hry
        refine hbet (r + x.length) (by omega) (by omega) ?_
        exact (markedAt_append P x y (r + x.length)).2 (Or.inr ⟨by omega, by simpa using hry⟩)
  -- two crossing witnesses have the same endpoints
  have huniq : ∀ p q p' q' : ℕ, p < q → p' < q' →
      markedAt P (x ++ y) p → markedAt P (x ++ y) q →
      (∀ r, p < r → r < q → ¬ markedAt P (x ++ y) r) →
      markedAt P (x ++ y) p' → markedAt P (x ++ y) q' →
      (∀ r, p' < r → r < q' → ¬ markedAt P (x ++ y) r) →
      p  < x.length → x.length ≤ q → p'  < x.length → x.length ≤ q' → p = p' ∧ q = q' := by
    intro p q p' q' hpq hpq' hp hq hbet hp' hq' hbet' hpL hqL hpL' hqL'
    have hpp : p = p' := by
      rcases lt_trichotomy p p' with h | h | h
      · exact absurd hp' (hbet p' h (by omega))
      · exact h
      · exact absurd hp (hbet' p h (by omega))
    subst hpp
    have hqq : q = q' := by
      rcases lt_trichotomy q q' with h | h | h
      · exact absurd hq (hbet' q (by omega) h)
      · exact h
      · exact absurd hq' (hbet q' (by omega) h)
    exact ⟨rfl, hqq⟩
  by_cases hE : (gaps P (x ++ y) \ (gaps P x ∪ gaps P y)).Nonempty
  · obtain ⟨d, hd⟩ := hE
    refine ⟨d, ?_⟩
    intro i hi
    by_cases hmem : i ∈ gaps P x ∪ gaps P y
    · exact Or.inl hmem
    · refine Or.inr ?_
      -- both `i` and `d` come from crossing witnesses, which coincide
      obtain ⟨p, q, hpq, hp, hq, hbet, hieq⟩ := hi
      obtain ⟨p', q', hpq', hp', hq', hbet', hdeq⟩ := hd.1
      have hcross : p  < x.length ∧ x.length ≤ q := by
        by_contra h
        exact hmem (hnc i ⟨p, q, hpq, hp, hq, hbet, hieq⟩ p q hpq hp hq hbet hieq h)
      have hcross' : p'  < x.length ∧ x.length ≤ q' := by
        by_contra h
        exact hd.2 (hnc d hd.1 p' q' hpq' hp' hq' hbet' hdeq h)
      obtain ⟨h1, h2⟩ := huniq p q p' q' hpq hpq' hp hq hbet hp' hq' hbet'
        hcross.1 hcross.2 hcross'.1 hcross'.2
      simp only [Set.mem_singleton_iff]
      omega
  · refine ⟨0, ?_⟩
    intro i hi
    by_cases hmem : i ∈ gaps P x ∪ gaps P y
    · exact Or.inl hmem
    · exact absurd ⟨i, hi, hmem⟩ hE

/-- The one distance that a rule `X → Y Z` can contribute. -/
noncomputable def crossD (P : A → Prop) (x y : List A) : ℕ := (gaps_append P x y).choose

lemma gaps_append_subset (P : A → Prop) (x y : List A) :
    gaps P (x ++ y) ⊆ gaps P x ∪ gaps P y ∪ {crossD P x y} := (gaps_append P x y).choose_spec

/-- The distance contributed by the `m`-th rule of a compression. -/
noncomputable def slpCross (P : A → Prop) (rs : List (Rule A)) (m : ℕ) : ℕ :=
  match rs[m]? with
  | some (Rule.cat j k) => crossD P (slpVal rs j) (slpVal rs k)
  | _ => 0

/-- All the distances that the first `i+1` rules of a compression can
contribute. -/
noncomputable def slpGapSet (P : A → Prop) (rs : List (Rule A)) (i : ℕ) : Finset ℕ :=
  (Finset.range (i + 1)).image (slpCross P rs)

lemma slpGapSet_card (P : A → Prop) (rs : List (Rule A)) (i : ℕ) :
    (slpGapSet P rs i).card ≤ i + 1 :=
  le_trans (Finset.card_image_le) (by simp)

lemma slpGapSet_mono (P : A → Prop) (rs : List (Rule A)) {i j : ℕ} (h : i ≤ j) :
    slpGapSet P rs i ⊆ slpGapSet P rs j := by
  apply Finset.image_subset_image
  intro n hn
  simp only [Finset.mem_range] at hn ⊢
  omega

/-- **The claim of the solution.**  The distances between consecutive marked
letters of the string generated by a rule are among the distances contributed by
that rule and the earlier ones; in particular there are at most as many of them
as there are rules. -/
lemma gaps_slpVal_subset (P : A → Prop) (rs : List (Rule A)) :
    ∀ i, gaps P (slpVal rs i) ⊆ ↑(slpGapSet P rs i) := by
  intro i
  induction i using Nat.strong_induction_on with
  | _ i ih =>
    match hr : rs[i]? with
    | none =>
      rw [slpVal, hr]
      rintro n ⟨p, q, _, hp, _, _, _⟩
      exact absurd (markedAt_lt hp) (by simp)
    | some (Rule.letter a) =>
      rw [slpVal_letter hr]
      rintro n ⟨p, q, hpq, hp, hq, _, _⟩
      have h1 := markedAt_lt hp
      have h2 := markedAt_lt hq
      simp only [List.length_cons, List.length_nil] at h1 h2
      omega
    | some (Rule.cat j k) =>
      by_cases hjk : j < i ∧ k < i
      · rw [slpVal_cat hr hjk.1 hjk.2]
        intro n hn
        rcases gaps_append_subset P (slpVal rs j) (slpVal rs k) hn with (h | h) | h
        · exact slpGapSet_mono P rs (le_of_lt hjk.1) (ih j hjk.1 h)
        · exact slpGapSet_mono P rs (le_of_lt hjk.2) (ih k hjk.2 h)
        · simp only [Set.mem_singleton_iff] at h
          have : slpCross P rs i = crossD P (slpVal rs j) (slpVal rs k) := by
            rw [slpCross, hr]
          simp only [slpGapSet, Finset.coe_image, Set.mem_image, Finset.mem_coe,
            Finset.mem_range]
          exact ⟨i, by omega, by rw [this, ← h]⟩
      · rw [slpVal, hr]
        simp only [hjk, dif_neg, not_false_iff]
        rintro n ⟨p, q, _, hp, _, _, _⟩
        exact absurd (markedAt_lt hp) (by simp)

/-- If the distances of a string include `S`, then every grammar compression of
that string has at least `S.card` rules. -/
lemma card_le_of_generates {P : A → Prop} {rs : List (Rule A)} {w : List A}
    (hgen : Generates rs w) {S : Finset ℕ} (hS : ↑S ⊆ gaps P w) : S.card ≤ rs.length := by
  have hsub : S ⊆ slpGapSet P rs (rs.length - 1) := by
    intro n hn
    have := gaps_slpVal_subset P rs (rs.length - 1) (hgen.2 ▸ hS (by simpa using hn))
    simpa using this
  have hcard := Finset.card_le_card hsub
  have := slpGapSet_card P rs (rs.length - 1)
  have hpos : 1 ≤ rs.length := List.length_pos_iff.2 hgen.1
  omega

/-! ## The compressions of a power of a letter -/

/-- The grammar compression of `a^(2ⁿ)` by repeated doubling: `n+1` rules. -/
def doubling (a : A) (n : ℕ) : List (Rule A) :=
  Rule.letter a :: (List.range n).map (fun m => Rule.cat m m)

lemma doubling_length (a : A) (n : ℕ) : (doubling a n).length = n + 1 := by
  simp [doubling]

lemma doubling_get (a : A) (n : ℕ) {m : ℕ} (hm : m < n) :
    (doubling a n)[m + 1]? = some (Rule.cat m m) := by
  simp [doubling, hm]

lemma doubling_get_zero (a : A) (n : ℕ) : (doubling a n)[0]? = some (Rule.letter a) := by
  simp [doubling]

lemma slpVal_doubling (a : A) (n : ℕ) :
    ∀ m ≤ n, slpVal (doubling a n) m = List.replicate (2 ^ m) a := by
  intro m
  induction m with
  | zero => intro _; rw [slpVal_letter (doubling_get_zero a n)]; simp
  | succ m ih =>
    intro hm
    rw [slpVal_cat (doubling_get a n (by omega)) (by omega) (by omega), ih (by omega)]
    rw [show 2 ^ (m + 1) = 2 ^ m + 2 ^ m by rw [pow_succ]; ring, List.replicate_add]

lemma generates_doubling (a : A) (n : ℕ) :
    Generates (doubling a n) (List.replicate (2 ^ n) a) := by
  refine ⟨by simp [doubling], ?_⟩
  rw [doubling_length]
  simpa using slpVal_doubling a n n le_rfl

/-! ## The marked square of a power of a letter -/

/-- The underlined letters of the output of marked squaring. -/
def IsUnderlined {A : Type} : A ⊕ A → Prop := fun z => ∃ a, z = Sum.inl a

/-- The marked square of `aᴺ`, as an explicit concatenation of blocks. -/
lemma markedSquare_replicate (N : ℕ) :
    markedSquare Unit (List.replicate N ()) =
      ((List.range N).map (fun i =>
        List.replicate (i + 1) (Sum.inl () : Unit ⊕ Unit) ++
          List.replicate (N - i - 1) (Sum.inr ()))).flatten := by
  rw [markedSquare]
  simp only [List.length_replicate]
  congr 1
  refine List.map_congr_left ?_
  intro i hi
  simp only [List.mem_range] at hi
  rw [List.take_replicate, List.drop_replicate]
  simp only [List.map_replicate]
  congr 2
  omega

/-- Between the last underlined letter of the `i`-th block and the first
underlined letter of the next block there are exactly `N - i - 1` letters that
are not underlined; so all the values `1, …, N-1` occur as distances. -/
lemma Ico_subset_gaps_markedSquare (N : ℕ) :
    ↑(Finset.Ico 1 N) ⊆ gaps IsUnderlined (markedSquare Unit (List.replicate N ())) := by
  intro d hd
  simp only [Finset.coe_Ico, Set.mem_Ico] at hd
  obtain ⟨hd1, hd2⟩ := hd
  set i := N - d - 1 with hi
  have hiN : i + 1 < N := by omega
  set f : ℕ → List (Unit ⊕ Unit) := fun i =>
    List.replicate (i + 1) (Sum.inl () : Unit ⊕ Unit) ++ List.replicate (N - i - 1) (Sum.inr ())
    with hf
  have hsplit : (List.range N).map f =
      ((List.range N).take i).map f ++ f i :: f (i + 1) :: ((List.range N).drop (i + 2)).map f := by
    have h1 : List.range N = (List.range N).take i ++ i :: (i + 1) :: (List.range N).drop (i + 2) := by
      have : (List.range N).drop i = i :: (i + 1) :: (List.range N).drop (i + 2) := by
        rw [List.drop_eq_getElem_cons (by simpa using (by omega : i < N)),
          List.drop_eq_getElem_cons (by simpa using (by omega : i + 1 < N))]
        simp
      conv_lhs => rw [← List.take_append_drop i (List.range N), this]
    conv_lhs => rw [h1]
    simp
  have hms := markedSquare_replicate N
  rw [← hf] at hms
  rw [hms, hsplit]
  simp only [List.flatten_append, List.flatten_cons]
  have hfi : f i = List.replicate i (Sum.inl () : Unit ⊕ Unit) ++
      Sum.inl () :: List.replicate (N - i - 1) (Sum.inr ()) := by
    rw [hf]
    simp only
    rw [show i + 1 = i + 1 from rfl, List.replicate_succ']
    simp
  have hfi1 : f (i + 1) = Sum.inl () :: (List.replicate (i + 1) (Sum.inl () : Unit ⊕ Unit) ++
      List.replicate (N - i - 2) (Sum.inr ())) := by
    rw [hf]
    simp only
    rw [show i + 1 + 1 = (i + 1) + 1 from rfl, List.replicate_succ]
    congr 2
  rw [hfi, hfi1]
  have hlen : (List.replicate (N - i - 1) (Sum.inr () : Unit ⊕ Unit)).length = d := by
    simp; omega
  rw [← hlen]
  refine mem_gaps_of_infix IsUnderlined
    (u := (List.map f (List.take i (List.range N))).flatten ++
      List.replicate i (Sum.inl () : Unit ⊕ Unit))
    (x := Sum.inl ()) (y := Sum.inl ())
    (z := List.replicate (N - i - 1) (Sum.inr ()))
    (v := List.replicate (i + 1) (Sum.inl ()) ++ List.replicate (N - i - 2) (Sum.inr ()) ++
      (List.map f (List.drop (i + 2) (List.range N))).flatten)
    ?_ ⟨(), rfl⟩ ⟨(), rfl⟩ ?_
  · simp [List.append_assoc]
  · intro c hc
    rintro ⟨a, ha⟩
    rw [List.eq_of_mem_replicate hc] at ha
    exact absurd ha (by simp)

/-! ### Exercise `exer:polyregular-marked-squaring-compression` -/

/-- **Exercise `exer:polyregular-marked-squaring-compression`.**  Marked squaring
is not compatible with compression: the input `a^(2ⁿ)` has a grammar compression
with `n+1` rules, while every grammar compression of its marked square has at
least `2ⁿ - 1` rules.  In particular no algorithm — a fortiori no polynomial-time
one — turns a compression of the input into a compression of the output. -/
theorem markedSquare_not_compatible_with_compression (n : ℕ) :
    ∃ w : List Unit,
      (∃ rs : List (Rule Unit), rs.length = n + 1 ∧ Generates rs w) ∧
      (∀ rs : List (Rule (Unit ⊕ Unit)), Generates rs (markedSquare Unit w) →
        2 ^ n - 1 ≤ rs.length) := by
  refine ⟨List.replicate (2 ^ n) (), ⟨doubling () n, doubling_length () n, generates_doubling () n⟩,
    ?_⟩
  intro rs hgen
  have := card_le_of_generates (P := IsUnderlined) hgen (Ico_subset_gaps_markedSquare (2 ^ n))
  simpa using this

end Exercises
end Transducers
