/-
Primitive recursiveness of the decision procedure of
`RequestProject/Exercises/IntComb.lean` (membership in the semigroup generated by a list of
integers).  The general-purpose arithmetic it rests on -- the `Primcodable` instance for `ℤ`
and the primitive recursiveness of addition, multiplication, comparison, gcd and divisibility on
`ℤ` -- is in `RequestProject/Common/PrimrecArith.lean`; nothing in that file is about
transducers.

The point of this file is `Transducers.Exercises.IntComb.primrec_meetsZ`: the procedure
`Transducers.Exercises.IntComb.meetsZ` is primitive recursive, hence computable.  The only
non-routine step is the bounded search `reachZ`, whose recursion nests a `List.any` inside a
recursive call; it is rewritten here as a `List.foldl` of the single step `reachStep` over the
list of generators, which is exactly the shape that `Primrec.list_foldl` accepts.
-/
import RequestProject.Exercises.IntComb
import RequestProject.Common.PrimrecArith

namespace Transducers.Exercises
namespace IntComb

open Primrec

/-- One step of the bounded search, on a whole list of targets at once. -/
def reachStep (L : List ℤ) (d : ℤ) : List ℤ :=
  L.flatMap (fun c => (List.range (c.toNat + 1)).map (fun n : ℕ => c - (n : ℤ) * d))

/-- Folding `reachStep` over the generators performs the whole search at once. -/
lemma reachZ_foldl : ∀ (ds : List ℤ) (L : List ℤ),
    (ds.foldl reachStep L).any (fun c => decide (c = 0)) = L.any (fun c => reachZ ds c) := by
  intro ds
  induction ds with
  | nil => intro L; rfl
  | cons d ds ih =>
      intro L
      rw [List.foldl_cons, ih (reachStep L d)]
      simp [reachStep, reachZ_cons, List.any_flatMap, List.any_map, Function.comp_def]

/-- The bounded search as a fold. -/
lemma reachZ_eq_foldl (ds : List ℤ) (c : ℤ) :
    reachZ ds c = ((ds.foldl reachStep [c]).any (fun x => decide (x = 0))) := by
  rw [reachZ_foldl ds [c]]
  simp

open Primrec in
/-- The single step of the search is primitive recursive. -/
theorem primrec_reachStep : Primrec₂ reachStep := by
  have h : Primrec fun p : List ℤ × ℤ =>
      p.1.flatMap (fun c => (List.range (c.toNat + 1)).map (fun n : ℕ => c - (n : ℤ) * p.2)) := by
    have h2 : Primrec fun q : (List ℤ × ℤ) × ℤ =>
        (List.range (q.2.toNat + 1)).map (fun n : ℕ => q.2 - (n : ℤ) * q.1.2) := by
      refine Primrec.list_map (f := fun q : (List ℤ × ℤ) × ℤ => List.range (q.2.toNat + 1))
        (g := fun (q : (List ℤ × ℤ) × ℤ) (n : ℕ) => q.2 - (n : ℤ) * q.1.2)
        (Primrec.list_range.comp (Primrec.succ.comp (int_toNat.comp snd))) ?_
      exact (int_sub.comp (snd.comp fst) (int_mul.comp (int_natCast.comp snd)
        (snd.comp (fst.comp fst)))).to₂
    exact Primrec.list_flatMap (f := fun p : List ℤ × ℤ => p.1)
      (g := fun (p : List ℤ × ℤ) (c : ℤ) => (List.range (c.toNat + 1)).map (fun n : ℕ => c - (n : ℤ) * p.2)) fst h2
  exact h

open Primrec in
/-- Testing a list of integers for an occurrence of `0` is primitive recursive. -/
theorem primrec_anyZero : Primrec (fun L : List ℤ => L.any (fun x => decide (x = 0))) := by
  have h : PrimrecPred (fun L : List ℤ => ∃ a ∈ L, a = 0) :=
    PrimrecPred.exists_mem_list (p := fun a : ℤ => a = 0)
      (PrimrecRel.comp (Primrec.eq (α := ℤ)) (Primrec.id (α := ℤ)) (const 0))
  refine h.decide.of_eq fun L => ?_
  rw [Bool.eq_iff_iff]
  simp only [decide_eq_true_eq, List.any_eq_true]

open Primrec in
/-- **The bounded search is primitive recursive.** -/
theorem primrec_reachZ : Primrec₂ reachZ := by
  have h : Primrec fun p : List ℤ × ℤ =>
      ((p.1.foldl reachStep [p.2]).any (fun x => decide (x = 0))) := by
    refine primrec_anyZero.comp ?_
    exact Primrec.list_foldl fst (list_cons.comp snd (const []))
      (primrec_reachStep.comp (fst.comp snd) (snd.comp snd)).to₂
  exact h.to₂.of_eq fun ds c => (reachZ_eq_foldl ds c).symm

/-- `listGcd` as a fold. -/
lemma listGcd_eq_foldr (ds : List ℤ) :
    listGcd ds = ds.foldr (fun d g => Int.gcd d (g : ℤ)) 0 := by
  induction ds with
  | nil => rfl
  | cons d ds ih => simp [listGcd_cons, ih]

open Primrec in
/-- The gcd of a list of integers is a primitive recursive function of the list. -/
theorem primrec_listGcd : Primrec listGcd := by
  have h : Primrec fun ds : List ℤ => ds.foldr (fun d g => Int.gcd d (g : ℤ)) 0 :=
    Primrec.list_foldr Primrec.id (const 0)
      (int_gcd.comp (fst.comp snd) (int_natCast.comp (snd.comp snd))).to₂
  exact h.of_eq fun ds => (listGcd_eq_foldr ds).symm

/-- `meetsZ` with its boolean tests spelled out as propositions. -/
lemma meetsZ_eq_ite (ds : List ℤ) (c : ℤ) :
    meetsZ ds c =
      if (∃ d ∈ ds, 0 < d) ∧ (∃ d ∈ ds, d < 0) then decide ((listGcd ds : ℤ) ∣ c)
      else if 0 ≤ c then reachZ ds c else reachZ (ds.map fun d => -d) (-c) := by
  rw [meetsZ]
  by_cases h : (∃ d ∈ ds, 0 < d) ∧ (∃ d ∈ ds, d < 0)
  · rw [if_pos h, if_pos]
    simpa [List.any_eq_true] using h
  · rw [if_neg h, if_neg]
    simpa [List.any_eq_true] using h

open Primrec in
/-- **The decision procedure of `RequestProject/Exercises/IntComb.lean` is primitive
recursive**, hence computable. -/
theorem primrec_meetsZ : Primrec₂ meetsZ := by
  have hpos : PrimrecPred fun p : List ℤ × ℤ => ∃ d ∈ p.1, (0 : ℤ) < d :=
    (PrimrecPred.exists_mem_list (p := fun d : ℤ => (0 : ℤ) < d)
      (PrimrecRel.comp int_lt (const (0:ℤ)) (Primrec.id (α := ℤ)))).comp fst
  have hneg : PrimrecPred fun p : List ℤ × ℤ => ∃ d ∈ p.1, d < (0 : ℤ) :=
    (PrimrecPred.exists_mem_list (p := fun d : ℤ => d < (0 : ℤ))
      (PrimrecRel.comp int_lt (Primrec.id (α := ℤ)) (const (0:ℤ)))).comp fst
  have hgcd : Primrec fun p : List ℤ × ℤ => decide ((listGcd p.1 : ℤ) ∣ p.2) :=
    (PrimrecRel.comp int_dvd (int_natCast.comp (primrec_listGcd.comp fst)) snd).decide
  have hnonneg : PrimrecPred fun p : List ℤ × ℤ => (0 : ℤ) ≤ p.2 :=
    PrimrecRel.comp int_le (const (0:ℤ)) snd
  have hneg' : Primrec fun p : List ℤ × ℤ => reachZ (p.1.map fun d => -d) (-p.2) :=
    primrec_reachZ.comp (Primrec.list_map fst (int_neg.comp snd).to₂) (int_neg.comp snd)
  have h : Primrec fun p : List ℤ × ℤ =>
      if (∃ d ∈ p.1, (0:ℤ) < d) ∧ (∃ d ∈ p.1, d < (0:ℤ)) then decide ((listGcd p.1 : ℤ) ∣ p.2)
      else if (0:ℤ) ≤ p.2 then reachZ p.1 p.2 else reachZ (p.1.map fun d => -d) (-p.2) :=
    Primrec.ite (hpos.and hneg) hgcd
      (Primrec.ite hnonneg (primrec_reachZ.comp fst snd) hneg')
  exact h.to₂.of_eq fun ds c => (meetsZ_eq_ite ds c).symm

end IntComb
end Transducers.Exercises
