/-
Nonnegative integer combinations of a finite list of integers, and the decidability of the
membership problem for the numerical semigroup they generate.

This is the arithmetic that item (b) of Exercise `exer:decide-rational-colision` of the chapter
on rational functions (`rational-functions.tex`) of *Transducers* (M. Bojańczyk) reduces to: the
pairs of output lengths of two rational functions form a semilinear subset of `ℕ × ℕ`, and the
exercise asks whether that set contains a pair with two equal coordinates.  Writing a linear set
as `b + ⟨p₁, …, p_k⟩`, a point of it lies on the diagonal exactly when

  `Σ nᵢ (pᵢ.1 - pᵢ.2) = b.2 - b.1`   for some `n₁, …, n_k ∈ ℕ`,

so the whole question is the membership problem for the sub-semigroup of `ℤ` generated by a
finite list of integers.  It is decided here in full (`Transducers.Exercises.IntComb.meetsZ` and
`Transducers.Exercises.IntComb.meetsZ_eq_true_iff`), by the classical case distinction:

* if the list contains both a positive and a negative integer, then the semigroup it generates is
  the whole subgroup generated by the list -- because each `-d` is itself a nonnegative
  combination -- so it is the set of multiples of the gcd of the list;
* otherwise all the generators have the same sign, and the coefficients of any representation of
  a target `c` are bounded by `|c|`, so a bounded search decides the question.

The use of this file is `RequestProject/Exercises/LengthCollision.lean`.
-/
import Mathlib

namespace Transducers
namespace Exercises
namespace IntComb

/-! ## Nonnegative combinations -/

/-- The value `Σ nᵢ dᵢ` of the coefficients `ns` against the generators `ds`.  Missing
coefficients count as zero. -/
def combVal : List ℤ → List ℕ → ℤ
  | [], _ => 0
  | _, [] => 0
  | d :: ds, n :: ns => (n : ℤ) * d + combVal ds ns

@[simp] lemma combVal_nil_left (ns : List ℕ) : combVal [] ns = 0 := by cases ns <;> rfl

@[simp] lemma combVal_nil_right (ds : List ℤ) : combVal ds [] = 0 := by cases ds <;> rfl

@[simp] lemma combVal_cons (d : ℤ) (ds : List ℤ) (n : ℕ) (ns : List ℕ) :
    combVal (d :: ds) (n :: ns) = (n : ℤ) * d + combVal ds ns := rfl

/-- `c` is a nonnegative integer combination of the generators `ds`. -/
def ZComb (ds : List ℤ) (c : ℤ) : Prop := ∃ ns : List ℕ, combVal ds ns = c

/-- The pointwise sum of two lists of coefficients, the shorter one padded with zeros. -/
def addCoeffs : List ℕ → List ℕ → List ℕ
  | [], ms => ms
  | ns, [] => ns
  | n :: ns, m :: ms => (n + m) :: addCoeffs ns ms

@[simp] lemma addCoeffs_nil_left (ms : List ℕ) : addCoeffs [] ms = ms := by cases ms <;> rfl

@[simp] lemma addCoeffs_nil_right (ns : List ℕ) : addCoeffs ns [] = ns := by cases ns <;> rfl

@[simp] lemma addCoeffs_cons (n : ℕ) (ns : List ℕ) (m : ℕ) (ms : List ℕ) :
    addCoeffs (n :: ns) (m :: ms) = (n + m) :: addCoeffs ns ms := rfl

lemma combVal_addCoeffs : ∀ (ds : List ℤ) (ns ms : List ℕ),
    combVal ds (addCoeffs ns ms) = combVal ds ns + combVal ds ms := by
  intro ds
  induction ds with
  | nil => intro ns ms; simp
  | cons d ds ih =>
      intro ns ms
      cases ns with
      | nil => simp
      | cons n ns =>
          cases ms with
          | nil => simp
          | cons m ms =>
              simp only [addCoeffs_cons, combVal_cons, ih ns ms, Nat.cast_add]
              ring

variable {ds : List ℤ}

lemma zComb_zero : ZComb ds 0 := ⟨[], by simp⟩

lemma ZComb.add {a b : ℤ} (ha : ZComb ds a) (hb : ZComb ds b) : ZComb ds (a + b) := by
  obtain ⟨ns, hns⟩ := ha
  obtain ⟨ms, hms⟩ := hb
  exact ⟨addCoeffs ns ms, by rw [combVal_addCoeffs, hns, hms]⟩

lemma ZComb.nsmul {a : ℤ} (ha : ZComb ds a) : ∀ n : ℕ, ZComb ds ((n : ℤ) * a) := by
  intro n
  induction n with
  | zero => simpa using (zComb_zero : ZComb ds 0)
  | succ n ih =>
      have := ih.add ha
      have h : ((n : ℤ) * a + a) = ((n + 1 : ℕ) : ℤ) * a := by push_cast; ring
      exact h ▸ this

/-- Every generator is a nonnegative combination of the generators. -/
lemma zComb_gen : ∀ {ds : List ℤ} {d : ℤ}, d ∈ ds → ZComb ds d := by
  intro ds
  induction ds with
  | nil => intro d hd; exact absurd hd (by simp)
  | cons e ds ih =>
      intro d hd
      rcases List.mem_cons.1 hd with rfl | hd
      · exact ⟨[1], by simp⟩
      · obtain ⟨ns, hns⟩ := ih hd
        exact ⟨0 :: ns, by simp [hns]⟩

lemma ZComb.cons {c : ℤ} (h : ZComb ds c) (d : ℤ) : ZComb (d :: ds) c := by
  obtain ⟨ns, hns⟩ := h
  exact ⟨0 :: ns, by simp [hns]⟩

/-! ## The gcd of the generators -/

/-- The gcd of a list of integers. -/
def listGcd : List ℤ → ℕ
  | [] => 0
  | d :: ds => Int.gcd d (listGcd ds : ℤ)

@[simp] lemma listGcd_nil : listGcd [] = 0 := rfl

@[simp] lemma listGcd_cons (d : ℤ) (ds : List ℤ) :
    listGcd (d :: ds) = Int.gcd d (listGcd ds : ℤ) := rfl

lemma listGcd_dvd : ∀ {ds : List ℤ} {d : ℤ}, d ∈ ds → ((listGcd ds : ℤ) ∣ d) := by
  intro ds
  induction ds with
  | nil => intro d hd; exact absurd hd (by simp)
  | cons e ds ih =>
      intro d hd
      rcases List.mem_cons.1 hd with rfl | hd
      · simpa using Int.gcd_dvd_left d (listGcd ds : ℤ)
      · exact dvd_trans (by simpa using Int.gcd_dvd_right e (listGcd ds : ℤ)) (ih hd)

lemma dvd_combVal {g : ℤ} : ∀ (ds : List ℤ) (ns : List ℕ), (∀ d ∈ ds, g ∣ d) →
    g ∣ combVal ds ns := by
  intro ds
  induction ds with
  | nil => intro ns _; simp
  | cons d ds ih =>
      intro ns hds
      cases ns with
      | nil => simp
      | cons n ns =>
          refine dvd_add (Dvd.dvd.mul_left (hds d (by simp)) _) (ih ns ?_)
          intro x hx
          exact hds x (by simp [hx])

/-! ## The mixed case: the generators have both signs -/

section Mixed

variable {p q : ℤ} (hp : p ∈ ds) (hp0 : 0 < p) (hq : q ∈ ds) (hq0 : q < 0)

include hp hp0 hq hq0

/-- If the generators contain a positive and a negative integer, then the opposite of every
generator is again a nonnegative combination of them. -/
lemma zComb_neg_gen {d : ℤ} (hd : d ∈ ds) : ZComb ds (-d) := by
  rcases le_or_gt 0 d with hd0 | hd0
  · have h₁ : ZComb ds (((q.natAbs - 1 : ℕ) : ℤ) * d) := (zComb_gen hd).nsmul _
    have h₂ : ZComb ds ((d.natAbs : ℤ) * q) := (zComb_gen hq).nsmul _
    have hqabs : (q.natAbs : ℤ) = -q := by omega
    have hq1 : 1 ≤ q.natAbs := by
      rcases Nat.eq_zero_or_pos q.natAbs with h | h
      · exact absurd (Int.natAbs_eq_zero.1 h) (by omega)
      · exact h
    have hcast : ((q.natAbs - 1 : ℕ) : ℤ) = -q - 1 := by
      rw [Nat.cast_sub hq1, hqabs]; norm_num
    have hdabs : (d.natAbs : ℤ) = d := Int.natAbs_of_nonneg hd0
    have := h₁.add h₂
    have hval : ((q.natAbs - 1 : ℕ) : ℤ) * d + (d.natAbs : ℤ) * q = -d := by
      rw [hcast, hdabs]; ring
    exact hval ▸ this
  · have h₁ : ZComb ds (((p.toNat - 1 : ℕ) : ℤ) * d) := (zComb_gen hd).nsmul _
    have h₂ : ZComb ds (((-d).toNat : ℤ) * p) := (zComb_gen hp).nsmul _
    have hp1 : 1 ≤ p.toNat := by omega
    have hcast : ((p.toNat - 1 : ℕ) : ℤ) = p - 1 := by
      rw [Nat.cast_sub hp1]
      simp [Int.toNat_of_nonneg (le_of_lt hp0)]
    have hdcast : (((-d).toNat : ℕ) : ℤ) = -d := Int.toNat_of_nonneg (by omega)
    have := h₁.add h₂
    have hval : ((p.toNat - 1 : ℕ) : ℤ) * d + (((-d).toNat : ℕ) : ℤ) * p = -d := by
      rw [hcast, hdcast]; ring
    exact hval ▸ this

private lemma zComb_neg_aux : ∀ (ds' : List ℤ) (ns : List ℕ), (∀ d ∈ ds', d ∈ ds) →
    ZComb ds (-combVal ds' ns) := by
  intro ds'
  induction ds' with
  | nil => intro ns _; simpa using (zComb_zero : ZComb ds 0)
  | cons d ds' ih =>
      intro ns hsub
      cases ns with
      | nil => simpa using (zComb_zero : ZComb ds 0)
      | cons n ns =>
          have h₁ : ZComb ds ((n : ℤ) * (-d)) :=
            (zComb_neg_gen hp hp0 hq hq0 (hsub d (by simp))).nsmul _
          have h₂ : ZComb ds (-combVal ds' ns) :=
            ih ns (fun x hx => hsub x (by simp [hx]))
          have := h₁.add h₂
          have hval : (n : ℤ) * (-d) + -combVal ds' ns = -((n : ℤ) * d + combVal ds' ns) := by
            ring
          rw [combVal_cons]
          exact hval ▸ this

/-- If the generators contain a positive and a negative integer, the nonnegative combinations are
closed under taking opposites. -/
lemma zComb_neg {c : ℤ} (hc : ZComb ds c) : ZComb ds (-c) := by
  obtain ⟨ns, rfl⟩ := hc
  exact zComb_neg_aux hp hp0 hq hq0 ds ns (fun _ h => h)

/-- ... and hence under multiplication by an arbitrary integer. -/
lemma zComb_zmul {c : ℤ} (hc : ZComb ds c) (z : ℤ) : ZComb ds (z * c) := by
  rcases le_or_gt 0 z with hz | hz
  · have := hc.nsmul z.toNat
    rwa [Int.toNat_of_nonneg hz] at this
  · have h := (hc.nsmul (-z).toNat)
    rw [Int.toNat_of_nonneg (by omega : (0 : ℤ) ≤ -z)] at h
    have := zComb_neg hp hp0 hq hq0 h
    have hval : -(-z * c) = z * c := by ring
    exact hval ▸ this

private lemma zComb_listGcd_aux : ∀ ds' : List ℤ, (∀ d ∈ ds', d ∈ ds) →
    ZComb ds (listGcd ds' : ℤ) := by
  intro ds'
  induction ds' with
  | nil => simpa using (zComb_zero : ZComb ds 0)
  | cons d ds' ih =>
      intro hsub
      have hd : ZComb ds d := zComb_gen (hsub d (by simp))
      have hg : ZComb ds (listGcd ds' : ℤ) := ih (fun x hx => hsub x (by simp [hx]))
      have hbez : ((Int.gcd d (listGcd ds' : ℤ) : ℕ) : ℤ)
          = d * Int.gcdA d (listGcd ds' : ℤ) + (listGcd ds' : ℤ) * Int.gcdB d (listGcd ds' : ℤ) :=
        Int.gcd_eq_gcd_ab d (listGcd ds' : ℤ)
      have h₁ : ZComb ds (d * Int.gcdA d (listGcd ds' : ℤ)) := by
        have := zComb_zmul hp hp0 hq hq0 hd (Int.gcdA d (listGcd ds' : ℤ))
        rwa [mul_comm] at this
      have h₂ : ZComb ds ((listGcd ds' : ℤ) * Int.gcdB d (listGcd ds' : ℤ)) := by
        have := zComb_zmul hp hp0 hq hq0 hg (Int.gcdB d (listGcd ds' : ℤ))
        rwa [mul_comm] at this
      rw [listGcd_cons, hbez]
      exact h₁.add h₂

/-- **The mixed case.**  If the generators contain a positive and a negative integer, then the
nonnegative combinations of the generators are exactly the multiples of their gcd. -/
theorem zComb_iff_gcd_dvd (c : ℤ) : ZComb ds c ↔ ((listGcd ds : ℤ) ∣ c) := by
  constructor
  · rintro ⟨ns, rfl⟩
    exact dvd_combVal ds ns (fun d hd => listGcd_dvd hd)
  · rintro ⟨k, rfl⟩
    have h := zComb_zmul hp hp0 hq hq0 (zComb_listGcd_aux hp hp0 hq hq0 ds (fun _ h => h)) k
    rwa [mul_comm] at h

end Mixed

/-! ## The unmixed case: a bounded search -/

lemma combVal_nonneg : ∀ (ds : List ℤ) (ns : List ℕ), (∀ d ∈ ds, 0 ≤ d) →
    0 ≤ combVal ds ns := by
  intro ds
  induction ds with
  | nil => intro ns _; simp
  | cons d ds ih =>
      intro ns hds
      cases ns with
      | nil => simp
      | cons n ns =>
          have h₁ : 0 ≤ (n : ℤ) * d := mul_nonneg (by positivity) (hds d (by simp))
          have h₂ : 0 ≤ combVal ds ns := ih ns (fun x hx => hds x (by simp [hx]))
          simpa using add_nonneg h₁ h₂

lemma combVal_nonpos : ∀ (ds : List ℤ) (ns : List ℕ), (∀ d ∈ ds, d ≤ 0) →
    combVal ds ns ≤ 0 := by
  intro ds
  induction ds with
  | nil => intro ns _; simp
  | cons d ds ih =>
      intro ns hds
      cases ns with
      | nil => simp
      | cons n ns =>
          have h₁ : (n : ℤ) * d ≤ 0 := mul_nonpos_of_nonneg_of_nonpos (by positivity) (hds d (by simp))
          have h₂ : combVal ds ns ≤ 0 := ih ns (fun x hx => hds x (by simp [hx]))
          simpa using add_nonpos h₁ h₂

/-- The bounded search for a representation of `c` as a nonnegative combination of `ds`: the
first coefficient is looked for among `0, …, |c|`. -/
def reachZ : List ℤ → ℤ → Bool
  | [], c => decide (c = 0)
  | d :: ds, c => (List.range (c.toNat + 1)).any (fun n => reachZ ds (c - (n : ℤ) * d))

@[simp] lemma reachZ_nil (c : ℤ) : reachZ [] c = decide (c = 0) := rfl

lemma reachZ_cons (d : ℤ) (ds : List ℤ) (c : ℤ) :
    reachZ (d :: ds) c
      = (List.range (c.toNat + 1)).any (fun n => reachZ ds (c - (n : ℤ) * d)) := rfl

/-- The search is sound: whatever it finds really is a nonnegative combination. -/
lemma zComb_of_reachZ : ∀ (ds : List ℤ) (c : ℤ), reachZ ds c = true → ZComb ds c := by
  intro ds
  induction ds with
  | nil =>
      intro c h
      have : c = 0 := of_decide_eq_true h
      exact this ▸ (zComb_zero : ZComb [] 0)
  | cons d ds ih =>
      intro c h
      rw [reachZ_cons, List.any_eq_true] at h
      obtain ⟨n, -, hn⟩ := h
      obtain ⟨ns, hns⟩ := ih _ hn
      refine ⟨n :: ns, ?_⟩
      rw [combVal_cons, hns]
      ring

lemma reachZ_zero : ∀ ds : List ℤ, reachZ ds 0 = true := by
  intro ds
  induction ds with
  | nil => simp
  | cons d ds ih =>
      rw [reachZ_cons, List.any_eq_true]
      exact ⟨0, by simp, by simpa using ih⟩

/-- The search is complete when all the generators are nonnegative. -/
lemma reachZ_of_zComb : ∀ (ds : List ℤ) (c : ℤ), (∀ d ∈ ds, 0 ≤ d) → 0 ≤ c → ZComb ds c →
    reachZ ds c = true := by
  intro ds
  induction ds with
  | nil =>
      rintro c - - ⟨ns, hns⟩
      simp only [combVal_nil_left] at hns
      simp [← hns]
  | cons d ds ih =>
      rintro c hds hc ⟨ns, hns⟩
      cases ns with
      | nil =>
          simp only [combVal_nil_right] at hns
          exact hns ▸ reachZ_zero (d :: ds)
      | cons n ns =>
          rw [combVal_cons] at hns
          have hd0 : 0 ≤ d := hds d (by simp)
          have hrest : 0 ≤ combVal ds ns :=
            combVal_nonneg ds ns (fun x hx => hds x (by simp [hx]))
          set n' : ℕ := if d = 0 then 0 else n with hn'
          have hval : (n' : ℤ) * d = (n : ℤ) * d := by
            by_cases hz : d = 0
            · simp [hn', hz]
            · simp [hn', hz]
          have hle : n' ≤ c.toNat := by
            by_cases hz : d = 0
            · simp [hn', hz]
            · have hd1 : 1 ≤ d := by omega
              have h1 : (n : ℤ) ≤ (n : ℤ) * d := le_mul_of_one_le_right (by positivity) hd1
              have h2 : (n : ℤ) * d ≤ c := by omega
              have : (n : ℤ) ≤ c := le_trans h1 h2
              simp only [hn', if_neg hz]
              omega
          rw [reachZ_cons, List.any_eq_true]
          refine ⟨n', by simp [List.mem_range]; omega, ?_⟩
          have hcc : c - (n' : ℤ) * d = combVal ds ns := by rw [hval]; omega
          rw [hcc]
          exact ih _ (fun x hx => hds x (by simp [hx])) hrest ⟨ns, rfl⟩

/-! ## Negating the generators -/

lemma combVal_map_neg : ∀ (ds : List ℤ) (ns : List ℕ),
    combVal (ds.map (fun d => -d)) ns = -combVal ds ns := by
  intro ds
  induction ds with
  | nil => intro ns; simp
  | cons d ds ih =>
      intro ns
      cases ns with
      | nil => simp
      | cons n ns => simp only [List.map_cons, combVal_cons, ih ns]; ring

lemma zComb_map_neg {c : ℤ} (h : ZComb ds c) : ZComb (ds.map (fun d => -d)) (-c) := by
  obtain ⟨ns, hns⟩ := h
  exact ⟨ns, by rw [combVal_map_neg, hns]⟩

/-! ## The decision procedure -/

/-- **The decision procedure for membership in the semigroup generated by a list of integers.**
If the list has both a positive and a negative element, the answer is whether the gcd of the list
divides the target; otherwise a bounded search suffices. -/
def meetsZ (ds : List ℤ) (c : ℤ) : Bool :=
  if (ds.any fun d => decide (0 < d)) && (ds.any fun d => decide (d < 0)) then
    decide ((listGcd ds : ℤ) ∣ c)
  else if 0 ≤ c then reachZ ds c
  else reachZ (ds.map fun d => -d) (-c)

/-- **The decision procedure is correct.** -/
theorem meetsZ_eq_true_iff (ds : List ℤ) (c : ℤ) : meetsZ ds c = true ↔ ZComb ds c := by
  rw [meetsZ]
  by_cases hmix : (ds.any fun d => decide (0 < d)) && (ds.any fun d => decide (d < 0))
  · rw [if_pos hmix]
    rw [Bool.and_eq_true] at hmix
    obtain ⟨hpos, hneg⟩ := hmix
    obtain ⟨p, hp, hp0⟩ := List.any_eq_true.1 hpos
    obtain ⟨q, hq, hq0⟩ := List.any_eq_true.1 hneg
    rw [decide_eq_true_iff]
    exact (zComb_iff_gcd_dvd hp (of_decide_eq_true hp0) hq (of_decide_eq_true hq0) c).symm
  · rw [if_neg hmix]
    have hcases : (∀ d ∈ ds, d ≤ 0) ∨ (∀ d ∈ ds, 0 ≤ d) := by
      by_cases h1 : (ds.any fun d => decide (0 < d)) = true
      · have h2 : (ds.any fun d => decide (d < 0)) = false := by
          rcases Bool.eq_false_or_eq_true (ds.any fun d => decide (d < 0)) with h | h
          · exact absurd (by rw [Bool.and_eq_true]; exact ⟨h1, h⟩) hmix
          · exact h
        right
        intro d hd
        by_contra hcon
        have hcon' : (ds.any fun d => decide (d < 0)) = true :=
          List.any_eq_true.2 ⟨d, hd, by simp; omega⟩
        rw [h2] at hcon'
        exact absurd hcon' (by simp)
      · left
        intro d hd
        by_contra hcon
        exact h1 (List.any_eq_true.2 ⟨d, hd, by simp; omega⟩)
    by_cases hc : 0 ≤ c
    · rw [if_pos hc]
      constructor
      · exact zComb_of_reachZ ds c
      · intro hz
        rcases hcases with hle | hge
        · obtain ⟨ns, hns⟩ := hz
          have : c ≤ 0 := hns ▸ combVal_nonpos ds ns hle
          have hc0 : c = 0 := by omega
          exact hc0 ▸ reachZ_zero ds
        · exact reachZ_of_zComb ds c hge hc hz
    · rw [if_neg hc]
      constructor
      · intro h
        have h' := zComb_of_reachZ _ _ h
        obtain ⟨ns, hns⟩ := h'
        rw [combVal_map_neg] at hns
        exact ⟨ns, by omega⟩
      · intro hz
        have h' : ZComb (ds.map fun d => -d) (-c) := zComb_map_neg hz
        rcases hcases with hle | hge
        · refine reachZ_of_zComb _ _ ?_ (by omega) h'
          intro d hd
          obtain ⟨e, he, rfl⟩ := List.mem_map.1 hd
          have := hle e he
          omega
        · obtain ⟨ns, hns⟩ := h'
          have hnp : combVal (ds.map fun d => -d) ns ≤ 0 := by
            refine combVal_nonpos _ ns ?_
            intro d hd
            obtain ⟨e, he, rfl⟩ := List.mem_map.1 hd
            have := hge e he
            omega
          omega

end IntComb
end Exercises
end Transducers
