#!/usr/bin/env python3
"""Give every exercise its own block, so its solution can be folded away.

`\\exer{statement}{solution}` (macros.sty) has always taken the solution as its
second argument, and has always thrown it away — the two lines that would typeset
it are commented out, so the solutions exist in the sources and appear nowhere.
The web edition can do better than the printed one here: show the exercise, and
let the reader ask for the solution.

Folding needs something to fold. A chapter is compiled as one `{{< latex >}}`
block and arrives in the browser as a single rendered unit, so a solution buried
inside it has no element of its own to hide — the reflowtex viewer lays the whole
chapter out as a flat run of line-level <svg> segments, and picking the ones that
belong to a particular solution means guessing at a range. So each exercise, and
each solution, is emitted as its own small block instead. Blocks are already
independent (see layouts/partials/latex-file-block.html), which makes the fold an
ordinary <details>.

That is why the chapter body is rendered with

    \\renewcommand{\\exer}[2]{}

which drops the exercises from the chapter's own block — they are re-emitted
below it, one block each, in source order. `\\exerciseheader` stays in the body
block, so the "Exercises" heading is still typeset by LaTeX, in the book's own
font, exactly where it was.

Numbering is set rather than counted: amsthm gives `exercise` the section as its
parent counter (`\\newtheorem{exercise}{Exercise}[section]`) and `\\thesection` is
`\\Alph{mypart}.\\arabic{section}`, so an exercise block only has to set mypart,
section and the exercise counter to land on the same number the printed edition
gives it. The first two come from the page's own \\setcounter lines, which
build-references.py maintains; the third is the exercise's position in its
chapter.

    python3 build-exercises.py           # report; exit 1 if content/ has drifted
    python3 build-exercises.py --write   # …and rewrite the exercise sections

rebuild.sh passes --write, so the blocks follow the sources by themselves;
running it bare is the read-only check.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent      # html/
BODY = ROOT.parent                          # the book repo root
CONTENT = ROOT / "content"

BEGIN = "<!-- exercises: generated by build-exercises.py; do not edit by hand -->"
END = "<!-- end exercises -->"
SUPPRESS = "\\renewcommand{\\exer}[2]{}"    # …in the chapter's own block


def blank_comments(text):
    """Comments blanked to spaces, keeping length, so brace counting is safe."""
    return re.sub(r"(?<!\\)%[^\n]*", lambda m: " " * len(m.group(0)), text)


def brace_arg(text, scan, i):
    """The {…} group starting at i, as (body, index just past it)."""
    if i >= len(scan) or scan[i] != "{":
        return None, i
    depth, j = 0, i
    while j < len(scan):
        if scan[j] == "{" and (j == 0 or scan[j - 1] != "\\"):
            depth += 1
        elif scan[j] == "}" and scan[j - 1] != "\\":
            depth -= 1
            if depth == 0:
                return text[i + 1:j], j + 1
        j += 1
    return None, i                          # unbalanced; caller reports it


# theorem, lemma, claim … all share one counter (macros.sty aliases them to
# `theorem`), so counting the environments counts the numbers they consume
RESULT_ENV = re.compile(r"\\begin\{(?:theorem|lemma|claim|corollary|definition"
                        r"|fact|proposition|conjecture|subclaim)\}")


def count_results(tex):
    return len(RESULT_ENV.findall(blank_comments(tex)))


def exercises_in(path):
    r"""([(statement, solution)], the chapter with the \exer calls cut out)."""
    text = path.read_text(errors="ignore")
    scan = blank_comments(text)
    out, body, cut = [], [], 0
    for m in re.finditer(r"\\exer\s*(?=\{)", scan):
        stmt, i = brace_arg(text, scan, m.end())
        if stmt is None:
            sys.exit(f"{path.name}: unbalanced braces in \\exer near offset {m.start()}")
        while i < len(scan) and scan[i].isspace():
            i += 1
        sol, j = brace_arg(text, scan, i)
        out.append((stmt.strip(), (sol or "").strip()))
        body.append(text[cut:m.start()])
        cut = j
    body.append(text[cut:])
    return out, "".join(body)


def read_page(md):
    """The bits of a content page this script needs, or None if it has no chapter."""
    text = md.read_text(errors="ignore")
    src = re.search(r'^source\s*=\s*"([^"]+)"', text, re.M)
    shortcode = re.search(r"\{\{<\s*latex\b[^>]*>\}\}", text)
    if not src or not shortcode:
        return None
    counters = {}
    for name in ("mypart", "section"):
        c = re.search(rf"\\setcounter\{{{name}\}}\{{(\d+)\}}", text)
        counters[name] = int(c.group(1)) if c else 0
    return {"text": text, "source": src.group(1), "open": shortcode.group(0),
            "counters": counters}


def render(page, chapter, items, body):
    """The generated exercise section for one page."""
    # the chapter's own \section commands have run by the time the exercises
    # appear, so the section counter has moved on from the page's opening value
    nsections = len(re.findall(r"^\\section\{", chapter.read_text(errors="ignore"), re.M))
    part = page["counters"]["mypart"]
    section = page["counters"]["section"] + nsections
    preamble = (f"\\setcounter{{mypart}}{{{part}}}"
                f"\\setcounter{{section}}{{{section}}}")

    # A result stated inside an exercise or a solution shares the book's one
    # theorem counter, and each block is compiled on its own — so without this
    # the first claim in a solution comes out as ".0.1", colliding with the
    # chapter's own Definition .0.1. The printed edition never shows it (\exer
    # discards its solution), so there is no number to match: the honest thing
    # is to carry on from where the chapter body left off.
    running = count_results(body)

    lines = [BEGIN, '<div class="exercises">']
    for n, (stmt, sol) in enumerate(items, 1):
        lines += [f'<div class="exercise" id="exercise-{n}">', page["open"],
                  f"{preamble}\\setcounter{{theorem}}{{{running}}}"
                  f"\\setcounter{{exercise}}{{{n - 1}}}",
                  "\\begin{exercise}", stmt, "\\end{exercise}", "{{< /latex >}}"]
        running += count_results(stmt)
        if sol:
            lines += ['<details class="solution">',
                      "<summary>Show solution</summary>",
                      '<div class="solution-body">', page["open"],
                      preamble + f"\\setcounter{{theorem}}{{{running}}}",
                      "\\noindent\\textbf{Solution.}\\quad " + sol,
                      "{{< /latex >}}", "</div>", "</details>"]
            running += count_results(sol)
        lines.append("</div>")
    lines += ["</div>", END]
    return "\n".join(lines) + "\n"


def rewrite(page, block):
    """The page with the exercise section, and the \\exer suppression, in place."""
    text = page["text"]
    if SUPPRESS not in text:
        # into the chapter's own block, just before it reads the chapter
        # a lambda, not a replacement string: SUPPRESS is full of backslashes
        text = re.sub(r"^\\input\{\.\./\.\./\.\./",
                      lambda m: SUPPRESS + "\n" + m.group(0), text,
                      count=1, flags=re.M)
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        text = head + block + rest.split(END, 1)[1].lstrip("\n")
    else:
        text = text.rstrip("\n") + "\n\n" + block
    return text


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true",
                    help="rewrite the exercise sections as well as reporting")
    args = ap.parse_args()

    total = solved = drifted = 0
    for md in sorted(CONTENT.glob("*.md")):
        page = read_page(md)
        if not page:
            continue
        chapter = BODY / page["source"]
        if not chapter.exists():
            print(f"  {md.name}: source {page['source']} not found", file=sys.stderr)
            drifted += 1
            continue
        items, body = exercises_in(chapter)
        if not items:
            continue
        block = render(page, chapter, items, body)
        want = rewrite(page, block)
        total += len(items)
        solved += sum(1 for _, s in items if s)
        n_sol = sum(1 for _, s in items if s)
        print(f"  {md.name:42s} {len(items):2d} exercise(s), {n_sol} with a solution")
        if want != page["text"]:
            drifted += 1
            if args.write:
                md.write_text(want)

    print(f"{total} exercises, {solved} with a solution written")
    if drifted and not args.write:
        print(f"{drifted} page(s) are out of step — run with --write")
        return 1
    if args.write:
        print("content pages updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
