/-
The label-indexed view of the formalisation.

The results of *Transducers* (M. Bojańczyk) are referred to throughout this
project by their LaTeX labels rather than by their numbers, which change
whenever the sources are edited (see `LABELS.md`).  This file makes that
correspondence part of the Lean development: for every formalised numbered
result, it declares an alias whose Lean name *is* the label of the result, so
the compiler checks that the declaration named in the documentation exists and
has the stated form.  The results themselves keep their descriptive Lean names;
nothing here is used in a proof.

Each alias is followed by a report of whether the result is proved outright:
`assert_no_sorry` fails if the declaration depends on `sorryAx`, and the
statements that are formalised but not yet proved carry `assert_uses_sorry`
instead.  So the status recorded in `THEOREMS.md` is checked here too.

Where a result of the book is formalised by several declarations, the first one
carries the label and the others carry the label followed by `#2`, `#3`, ....

This file is generated by `tools/gen_labels.py` from the status tables of
`THEOREMS.md`; edit those, not this file.
-/
import RequestProject.Common
import RequestProject.PartA
import RequestProject.PartB
import RequestProject.PartC
import RequestProject.PartD
import RequestProject.Exercises

namespace Transducers.Book

open Lean Elab Command in
/-- `assert_no_sorry foo` fails unless `foo` is proved without `sorry`. -/
elab "assert_no_sorry " id:ident : command => do
  let n ← liftCoreM <| realizeGlobalConstNoOverload id
  let axs ← liftCoreM <| Lean.collectAxioms n
  if axs.contains ``sorryAx then
    throwError "{n} depends on sorryAx"

open Lean Elab Command in
/-- `assert_uses_sorry foo` fails unless `foo` still depends on `sorry`.  It
marks the statements of the book that are formalised but not proved yet. -/
elab "assert_uses_sorry " id:ident : command => do
  let n ← liftCoreM <| realizeGlobalConstNoOverload id
  let axs ← liftCoreM <| Lean.collectAxioms n
  if !axs.contains ``sorryAx then
    throwError "{n} does not depend on sorryAx"


/-- **Definition `def:continuity`** (continuity): `Transducers.Continuous`. -/
alias «def:continuity» := Transducers.Continuous
assert_no_sorry «def:continuity»

/-- **Definition `def:mealy-machine`** (Mealy machine): `Transducers.Mealy`. -/
alias «def:mealy-machine» := Transducers.Mealy
assert_no_sorry «def:mealy-machine»

/-- **Definition `def:mealy-machine`** (Mealy machine): `Transducers.Mealy.eval`. -/
alias «def:mealy-machine#2» := Transducers.Mealy.eval
assert_no_sorry «def:mealy-machine#2»

/-- **Definition `def:mealy-machine`** (Mealy machine): `Transducers.IsMealy`. -/
alias «def:mealy-machine#3» := Transducers.IsMealy
assert_no_sorry «def:mealy-machine#3»

/-- **Theorem `thm:equivalence-decidable-mealy`** (decidable equivalence): `Transducers.mealy_equiv_iff_bounded`. -/
alias «thm:equivalence-decidable-mealy» := Transducers.mealy_equiv_iff_bounded
assert_no_sorry «thm:equivalence-decidable-mealy»

/-- **Theorem `thm:composition-mealy`** (composition): `Transducers.mealy_comp`. -/
alias «thm:composition-mealy» := Transducers.mealy_comp
assert_no_sorry «thm:composition-mealy»

/-- **Theorem `thm:continuity-mealy`** (continuity): `Transducers.mealy_continuous`. -/
alias «thm:continuity-mealy» := Transducers.mealy_continuous
assert_no_sorry «thm:continuity-mealy»

/-- **Definition `nolabel:def-prime-mealy-machines`** (prime Mealy machines): `Transducers.Mealy.Reversible`. -/
alias «nolabel:def-prime-mealy-machines» := Transducers.Mealy.Reversible
assert_no_sorry «nolabel:def-prime-mealy-machines»

/-- **Definition `nolabel:def-prime-mealy-machines`** (prime Mealy machines): `Transducers.Mealy.FlipFlop`. -/
alias «nolabel:def-prime-mealy-machines#2» := Transducers.Mealy.FlipFlop
assert_no_sorry «nolabel:def-prime-mealy-machines#2»

/-- **Definition `nolabel:def-prime-mealy-machines`** (prime Mealy machines): `Transducers.PrimeMealyFam`. -/
alias «nolabel:def-prime-mealy-machines#3» := Transducers.PrimeMealyFam
assert_no_sorry «nolabel:def-prime-mealy-machines#3»

/-- **Theorem `nolabel:thm-krohn-rhodes`** (Krohn–Rhodes): `Transducers.krohn_rhodes`. -/
alias «nolabel:thm-krohn-rhodes» := Transducers.krohn_rhodes
assert_no_sorry «nolabel:thm-krohn-rhodes»

/-- **Definition `def:map-lifting`** (map lifting): `Transducers.mapLift`. -/
alias «def:map-lifting» := Transducers.mapLift
assert_no_sorry «def:map-lifting»

/-- **Lemma `lem:map-lifting-decomposition-mealy`** (map lifting of a decomposition): `Transducers.mapLift_prime_decomposition`. -/
alias «lem:map-lifting-decomposition-mealy» := Transducers.mapLift_prime_decomposition
assert_no_sorry «lem:map-lifting-decomposition-mealy»

/-- **Lemma `lem:Mealy-map-lifting`** (state transformation transducer): `Transducers.stateTransTransducer_prime_decomposition`. -/
alias «lem:Mealy-map-lifting» := Transducers.stateTransTransducer_prime_decomposition
assert_no_sorry «lem:Mealy-map-lifting»

/-- **Lemma `lem:reversible-composition`** (reversible machines compose): `Transducers.reversible_comp`. -/
alias «lem:reversible-composition» := Transducers.reversible_comp
assert_no_sorry «lem:reversible-composition»

/-- **Definition `def:aperiodic-mealy`** (aperiodic): `Transducers.Aperiodic`. -/
alias «def:aperiodic-mealy» := Transducers.Aperiodic
assert_no_sorry «def:aperiodic-mealy»

/-- **Theorem `thm:aperiodic-mealy`** (aperiodic = flip-flops): `Transducers.aperiodic_iff_flipflop_composition`. -/
alias «thm:aperiodic-mealy» := Transducers.aperiodic_iff_flipflop_composition
assert_no_sorry «thm:aperiodic-mealy»

/-- **Claim `nolabel:claim-aperiodic-pumping`** (pumping form of aperiodicity): `Transducers.aperiodic_iff_pumping`. -/
alias «nolabel:claim-aperiodic-pumping» := Transducers.aperiodic_iff_pumping
assert_no_sorry «nolabel:claim-aperiodic-pumping»

/-- **Lemma `lemma:derivatives`** (Myhill–Nerode): `Transducers.myhill_nerode_mealy`. -/
alias «lemma:derivatives» := Transducers.myhill_nerode_mealy
assert_no_sorry «lemma:derivatives»

/-- **Lemma `lem:aperiodicity-minimal-machine`** (condition (*)): `Transducers.aperiodic_iff_transStabilises`. -/
alias «lem:aperiodicity-minimal-machine» := Transducers.aperiodic_iff_transStabilises
assert_no_sorry «lem:aperiodicity-minimal-machine»

/-- **Definition `nolabel:def-nfa-with-output`** (nfa with output): `Transducers.NFAO`. -/
alias «nolabel:def-nfa-with-output» := Transducers.NFAO
assert_no_sorry «nolabel:def-nfa-with-output»

/-- **Definition `nolabel:def-nfa-with-output`** (nfa with output): `Transducers.LabAut`. -/
alias «nolabel:def-nfa-with-output#2» := Transducers.LabAut
assert_no_sorry «nolabel:def-nfa-with-output#2»

/-- **Definition `def:rational-relation`** (rational relation): `Transducers.IsRationalRel`. -/
alias «def:rational-relation» := Transducers.IsRationalRel
assert_no_sorry «def:rational-relation»

/-- **Theorem `thm:composition-rational-relations`** (composition): `Transducers.rationalRel_comp`. -/
alias «thm:composition-rational-relations» := Transducers.rationalRel_comp
assert_no_sorry «thm:composition-rational-relations»

/-- **Theorem `thm:continuity-rational-relations`** (continuity): `Transducers.rationalRel_continuous`. -/
alias «thm:continuity-rational-relations» := Transducers.rationalRel_continuous
assert_no_sorry «thm:continuity-rational-relations»

/-- **Theorem `thm:undecidable-equivalence-rational-relations`** (undecidable equivalence): `Transducers.rationalRel_equivalence_undecidable`. -/
alias «thm:undecidable-equivalence-rational-relations» := Transducers.rationalRel_equivalence_undecidable
assert_no_sorry «thm:undecidable-equivalence-rational-relations»

/-- **Claim `nolabel:claim-complement-of-homomorphism`** (complement of a homomorphism): `Transducers.hom_complement_rational`. -/
alias «nolabel:claim-complement-of-homomorphism» := Transducers.hom_complement_rational
assert_no_sorry «nolabel:claim-complement-of-homomorphism»

/-- **Definition `nolabel:def-rational-function`** (rational function): `Transducers.IsRationalFun`. -/
alias «nolabel:def-rational-function» := Transducers.IsRationalFun
assert_no_sorry «nolabel:def-rational-function»

/-- **Definition `def:bimachine`** (bimachine): `Transducers.Bimachine`. -/
alias «def:bimachine» := Transducers.Bimachine
assert_no_sorry «def:bimachine»

/-- **Definition `def:bimachine`** (bimachine): `Transducers.IsBimachine`. -/
alias «def:bimachine#2» := Transducers.IsBimachine
assert_no_sorry «def:bimachine#2»

/-- **Theorem `thm:bimachines`** (rational = unambiguous = bimachine): `Transducers.rational_iff_unambiguous_iff_bimachine`. -/
alias «thm:bimachines» := Transducers.rational_iff_unambiguous_iff_bimachine
assert_no_sorry «thm:bimachines»

/-- **Lemma `lemma:eliminate-epsilon-transitions`** (elimination of ε-transitions): `Transducers.epsilon_elimination`. -/
alias «lemma:eliminate-epsilon-transitions» := Transducers.epsilon_elimination
assert_no_sorry «lemma:eliminate-epsilon-transitions»

/-- **Lemma `lem:uniformisation`** (uniformisation): `Transducers.uniformisation`. -/
alias «lem:uniformisation» := Transducers.uniformisation
assert_no_sorry «lem:uniformisation»

/-- **Theorem `thm:rational-primes`** (decomposition into primes): `Transducers.rational_iff_prime_composition`. -/
alias «thm:rational-primes» := Transducers.rational_iff_prime_composition
assert_no_sorry «thm:rational-primes»

/-- **Theorem `nolabel:thm-mealy-among-rational-functions`** (Mealy machines inside rational functions): `Transducers.rational_isMealy_iff`. -/
alias «nolabel:thm-mealy-among-rational-functions» := Transducers.rational_isMealy_iff
assert_no_sorry «nolabel:thm-mealy-among-rational-functions»

/-- **Definition `nolabel:def-semiring`** (semiring): `Semiring`.  Not a numbered result of its own here: Mathlib's `Semiring`. -/
alias «nolabel:def-semiring» := Semiring
assert_no_sorry «nolabel:def-semiring»

/-- **Definition `nolabel:def-weighted-automaton`** (weighted automaton): `Transducers.LabAut.wEval`. -/
alias «nolabel:def-weighted-automaton» := Transducers.LabAut.wEval
assert_no_sorry «nolabel:def-weighted-automaton»

/-- **Definition `nolabel:def-weighted-automaton`** (weighted automaton): `Transducers.IsWeighted`. -/
alias «nolabel:def-weighted-automaton#2» := Transducers.IsWeighted
assert_no_sorry «nolabel:def-weighted-automaton#2»

/-- **Theorem `thm:equivalence-weighted-automata`** (equivalence over ℚ): `Transducers.weighted_equivalence_decidable`. -/
alias «thm:equivalence-weighted-automata» := Transducers.weighted_equivalence_decidable
assert_no_sorry «thm:equivalence-weighted-automata»

/-- **Theorem `thm:equivalence-rational-functions`** (equivalence of rational functions): `Transducers.rationalFun_equivalence_decidable`. -/
alias «thm:equivalence-rational-functions» := Transducers.rationalFun_equivalence_decidable
assert_no_sorry «thm:equivalence-rational-functions»

/-- **Lemma `lem:closure-weighted-automata-precomposition`** (pre-composition): `Transducers.weighted_precomp_rational`. -/
alias «lem:closure-weighted-automata-precomposition» := Transducers.weighted_precomp_rational
assert_no_sorry «lem:closure-weighted-automata-precomposition»

/-- **Theorem `thm:characterisation-rational-functions-weighted-automata`** (characterisation of rationality): `Transducers.rational_iff_weighted_precomp`. -/
alias «thm:characterisation-rational-functions-weighted-automata» := Transducers.rational_iff_weighted_precomp
assert_no_sorry «thm:characterisation-rational-functions-weighted-automata»

/-- **Theorem `thm:zeroness-weighted-automata`** (zeroness): `Transducers.weighted_zeroness_decidable`. -/
alias «thm:zeroness-weighted-automata» := Transducers.weighted_zeroness_decidable
assert_no_sorry «thm:zeroness-weighted-automata»

/-- **Theorem `thm:mealy-machine-independent`** (characterisation of Mealy machines): `Transducers.isMealy_iff`. -/
alias «thm:mealy-machine-independent» := Transducers.isMealy_iff
assert_no_sorry «thm:mealy-machine-independent»

/-- **Theorem `thm:decide-if-mealy`** (deciding the Mealy fragment): `Transducers.rationalFun_isMealy_decidable`. -/
alias «thm:decide-if-mealy» := Transducers.rationalFun_isMealy_decidable
assert_no_sorry «thm:decide-if-mealy»

/-- **Lemma `lem:decide-if-length-preserving`** (deciding length preservation): `Transducers.rationalFun_lengthPreserving_decidable`. -/
alias «lem:decide-if-length-preserving» := Transducers.rationalFun_lengthPreserving_decidable
assert_no_sorry «lem:decide-if-length-preserving»

/-- **Claim `claim:typing-length-preserving`** (typings): `Transducers.lengthPreserving_iff_typing`. -/
alias «claim:typing-length-preserving» := Transducers.lengthPreserving_iff_typing
assert_no_sorry «claim:typing-length-preserving»

/-- **Lemma `lem:characterisation-length-preserving`** (length-preserving normal form): `Transducers.lengthPreserving_rational_normal_form`. -/
alias «lem:characterisation-length-preserving» := Transducers.lengthPreserving_rational_normal_form
assert_no_sorry «lem:characterisation-length-preserving»

/-- **Theorem `thm:sequential-function-independent`** (sequential functions): `Transducers.isSequential_iff`. -/
alias «thm:sequential-function-independent» := Transducers.isSequential_iff
assert_no_sorry «thm:sequential-function-independent»

/-- **Definition `nolabel:def-left-distance`** (left distance): `Transducers.leftDist`. -/
alias «nolabel:def-left-distance» := Transducers.leftDist
assert_no_sorry «nolabel:def-left-distance»

/-- **Theorem `thm:subsequential-functions`** (subsequential functions): `Transducers.isSubsequential_iff`. -/
alias «thm:subsequential-functions» := Transducers.isSubsequential_iff
assert_no_sorry «thm:subsequential-functions»

/-- **Theorem `thm:machine-independent-rational-functions`** (rational functions): `Transducers.isRationalFun_iff`. -/
alias «thm:machine-independent-rational-functions» := Transducers.isRationalFun_iff
assert_no_sorry «thm:machine-independent-rational-functions»

/-- **Definition `def:regular-functions`** (regular functions): `Transducers.IsRegularFun`. -/
alias «def:regular-functions» := Transducers.IsRegularFun
assert_no_sorry «def:regular-functions»

/-- **Definition `def:regular-functions`** (regular functions): `Transducers.RegularFam`. -/
alias «def:regular-functions#2» := Transducers.RegularFam
assert_no_sorry «def:regular-functions#2»

/-- **Theorem `thm:regular-functions-are-continuous-and-closed-under-composition`** (continuity, composition): `Transducers.regular_continuous`. -/
alias «thm:regular-functions-are-continuous-and-closed-under-composition» := Transducers.regular_continuous
assert_no_sorry «thm:regular-functions-are-continuous-and-closed-under-composition»

/-- **Theorem `thm:regular-functions-are-continuous-and-closed-under-composition`** (continuity, composition): `Transducers.regular_comp`. -/
alias «thm:regular-functions-are-continuous-and-closed-under-composition#2» := Transducers.regular_comp
assert_no_sorry «thm:regular-functions-are-continuous-and-closed-under-composition#2»

/-- **Lemma `nolabel:lem-reverse-and-duplicate-continuous`** (reversal, duplication): `Transducers.reverse_duplicate_continuous`. -/
alias «nolabel:lem-reverse-and-duplicate-continuous» := Transducers.reverse_duplicate_continuous
assert_no_sorry «nolabel:lem-reverse-and-duplicate-continuous»

/-- **Lemma `lem:map-lifting-continuous`** (map lifting): `Transducers.mapLift_continuous`. -/
alias «lem:map-lifting-continuous» := Transducers.mapLift_continuous
assert_no_sorry «lem:map-lifting-continuous»

/-- **Theorem `thm:decidable-equivalence-regular`** (decidable equivalence): `Transducers.regular_equivalence_decidable`. -/
alias «thm:decidable-equivalence-regular» := Transducers.regular_equivalence_decidable
assert_no_sorry «thm:decidable-equivalence-regular»

/-- **Definition `nolabel:def-two-way-transducer`** (two-way transducer): `Transducers.TwoWay`. -/
alias «nolabel:def-two-way-transducer» := Transducers.TwoWay
assert_no_sorry «nolabel:def-two-way-transducer»

/-- **Definition `nolabel:def-two-way-transducer`** (two-way transducer): `Transducers.IsTwoWay`. -/
alias «nolabel:def-two-way-transducer#2» := Transducers.IsTwoWay
assert_no_sorry «nolabel:def-two-way-transducer#2»

/-- **Theorem `thm:continuity-2dfas`** (continuity): `Transducers.twoWay_continuous`. -/
alias «thm:continuity-2dfas» := Transducers.twoWay_continuous
assert_no_sorry «thm:continuity-2dfas»

/-- **Theorem `thm:composition-of-two-way-transducers`** (composition): `Transducers.twoWay_comp`. -/
alias «thm:composition-of-two-way-transducers» := Transducers.twoWay_comp
assert_no_sorry «thm:composition-of-two-way-transducers»

/-- **Lemma `lem:2dfa-precomposition-with-mealy`** (pre-composition with Mealy machines): `Transducers.twoWay_precomp_mealy`. -/
alias «lem:2dfa-precomposition-with-mealy» := Transducers.twoWay_precomp_mealy
assert_no_sorry «lem:2dfa-precomposition-with-mealy»

/-- **Corollary `cor:2dfa-closure-under-composition`** (pre-composition with rational functions): `Transducers.twoWay_precomp_rational`. -/
alias «cor:2dfa-closure-under-composition» := Transducers.twoWay_precomp_rational
assert_no_sorry «cor:2dfa-closure-under-composition»

/-- **Corollary `nolabel:cor-two-way-implies-regular`** (regular ⊆ two-way): `Transducers.regularFun_isTwoWay`. -/
alias «nolabel:cor-two-way-implies-regular» := Transducers.regularFun_isTwoWay
assert_no_sorry «nolabel:cor-two-way-implies-regular»

/-- **Corollary `nolabel:cor-two-way-implies-regular`** (regular ⊆ two-way): `Transducers.isTwoWay_of_isRegularFun`. -/
alias «nolabel:cor-two-way-implies-regular#2» := Transducers.isTwoWay_of_isRegularFun
assert_no_sorry «nolabel:cor-two-way-implies-regular#2»

/-- **Theorem `thm:2dfa-decomposition-into-primes`** (two-way = regular): `Transducers.twoWay_iff_regular`. -/
alias «thm:2dfa-decomposition-into-primes» := Transducers.twoWay_iff_regular
assert_no_sorry «thm:2dfa-decomposition-into-primes»

/-- **Theorem `thm:2dfa-decomposition-into-primes`** (two-way = regular): `Transducers.twoWay_isRegular`. -/
alias «thm:2dfa-decomposition-into-primes#2» := Transducers.twoWay_isRegular
assert_no_sorry «thm:2dfa-decomposition-into-primes#2»

/-- **Lemma `lem:regular-closure-properties`** (closure properties): `Transducers.regular_closure_properties`. -/
alias «lem:regular-closure-properties» := Transducers.regular_closure_properties
assert_no_sorry «lem:regular-closure-properties»

/-- **Claim `claim:conditional`** (disjoint sums): `Transducers.sum_of_regular`. -/
alias «claim:conditional» := Transducers.sum_of_regular
assert_no_sorry «claim:conditional»

/-- **Definition `def:sst`** (sst): `Transducers.SST`. -/
alias «def:sst» := Transducers.SST
assert_no_sorry «def:sst»

/-- **Definition `def:sst`** (sst): `Transducers.IsSST`. -/
alias «def:sst#2» := Transducers.IsSST
assert_no_sorry «def:sst#2»

/-- **Theorem `theorem:sst-two-way-equivalence`** (sst = regular): `Transducers.sst_iff_regular`. -/
alias «theorem:sst-two-way-equivalence» := Transducers.sst_iff_regular
assert_no_sorry «theorem:sst-two-way-equivalence»

/-- **Theorem `thm:mso-logic-languages`** (mso = regular languages): `Transducers.regular_iff_msoDefinable`. -/
alias «thm:mso-logic-languages» := Transducers.regular_iff_msoDefinable
assert_no_sorry «thm:mso-logic-languages»

/-- **Lemma `nolabel:lem-mso-to-automaton`** (formulas with free variables): `Transducers.mso_annotated_regular`. -/
alias «nolabel:lem-mso-to-automaton» := Transducers.mso_annotated_regular
assert_no_sorry «nolabel:lem-mso-to-automaton»

/-- **Definition `def:mso-relabeling`** (mso relabelling): `Transducers.MSORelabelling`. -/
alias «def:mso-relabeling» := Transducers.MSORelabelling
assert_no_sorry «def:mso-relabeling»

/-- **Definition `def:mso-relabeling`** (mso relabelling): `Transducers.IsMSORelabelling`. -/
alias «def:mso-relabeling#2» := Transducers.IsMSORelabelling
assert_no_sorry «def:mso-relabeling#2»

/-- **Theorem `thm:logic-rational-functions`** (rational = mso relabelling): `Transducers.rational_iff_msoRelabelling`. -/
alias «thm:logic-rational-functions» := Transducers.rational_iff_msoRelabelling
assert_no_sorry «thm:logic-rational-functions»

/-- **Claim `claim:transition-formula`** (transition formula): `Transducers.RatRelab.exists_form`.  Not a numbered result of its own here: an internal step of Theorem `thm:logic-rational-functions`, stated for the index of a bimachine. -/
alias «claim:transition-formula» := Transducers.RatRelab.exists_form
assert_no_sorry «claim:transition-formula»

/-- **Claim `nolabel:claim-formula-annotation-regular`** (annotated relabellings): `Transducers.msoRelabelling_annotation_regular`. -/
alias «nolabel:claim-formula-annotation-regular» := Transducers.msoRelabelling_annotation_regular
assert_no_sorry «nolabel:claim-formula-annotation-regular»

/-- **Definition `def:mso-transduction`** (mso transduction): `Transducers.MSOTransduction`. -/
alias «def:mso-transduction» := Transducers.MSOTransduction
assert_no_sorry «def:mso-transduction»

/-- **Definition `def:mso-transduction`** (mso transduction): `Transducers.IsMSOTransduction`. -/
alias «def:mso-transduction#2» := Transducers.IsMSOTransduction
assert_no_sorry «def:mso-transduction#2»

/-- **Theorem `thm:logic-regular-functions`** (mso transductions = regular): `Transducers.msoTransduction_iff_regular`. -/
alias «thm:logic-regular-functions» := Transducers.msoTransduction_iff_regular
assert_no_sorry «thm:logic-regular-functions»

/-- **Lemma `lem:logic-reduction-to-type-n`** (reduction to type n): `Transducers.MSOTransduction.exists_norm`.  Not a numbered result of its own here: an internal step of Theorem `thm:logic-regular-functions`: the normalisation of the type. -/
alias «lem:logic-reduction-to-type-n» := Transducers.MSOTransduction.exists_norm
assert_no_sorry «lem:logic-reduction-to-type-n»

/-- **Lemma `lem:logic-precomputation`** (formulas via rational functions): `Transducers.mso_formulas_via_rational`. -/
alias «lem:logic-precomputation» := Transducers.mso_formulas_via_rational
assert_no_sorry «lem:logic-precomputation»

/-- **Theorem `thm:logic-aperiodic`** (first-order = aperiodic): `Transducers.foDefinable_iff_aperiodic_dfa`. -/
alias «thm:logic-aperiodic» := Transducers.foDefinable_iff_aperiodic_dfa
assert_no_sorry «thm:logic-aperiodic»

/-- **Definition `nolabel:def-fo-types`** (k-types): `Transducers.tp`. -/
alias «nolabel:def-fo-types» := Transducers.tp
assert_no_sorry «nolabel:def-fo-types»

/-- **Lemma `nolabel:lem-fo-types-characterisation`** (types and formulas): `Transducers.tp_eq_iff_fo_equiv`. -/
alias «nolabel:lem-fo-types-characterisation» := Transducers.tp_eq_iff_fo_equiv
assert_no_sorry «nolabel:lem-fo-types-characterisation»

/-- **Claim `nolabel:claim-fo-type-of-a-tuple`** (the type of a tuple): `Transducers.sat_iff_of_kEquiv`.  Not a numbered result of its own here: an internal step of Lemma `nolabel:lem-fo-types-characterisation`. -/
alias «nolabel:claim-fo-type-of-a-tuple» := Transducers.sat_iff_of_kEquiv
assert_no_sorry «nolabel:claim-fo-type-of-a-tuple»

/-- **Lemma `item:fo-types-more-information`** (properties of types): `Transducers.tp_properties`. -/
alias «item:fo-types-more-information» := Transducers.tp_properties
assert_no_sorry «item:fo-types-more-information»

/-- **Theorem `thm:fo-rational-functions`** (first-order relabellings): `Transducers.foRelabelling_iff_aperiodicBimachine`. -/
alias «thm:fo-rational-functions» := Transducers.foRelabelling_iff_aperiodicBimachine
assert_no_sorry «thm:fo-rational-functions»

/-- **Definition `def:polyregular-functions`** (polyregular functions): `Transducers.IsPolyregular`. -/
alias «def:polyregular-functions» := Transducers.IsPolyregular
assert_no_sorry «def:polyregular-functions»

/-- **Definition `def:polyregular-functions`** (polyregular functions): `Transducers.markedSquare`. -/
alias «def:polyregular-functions#2» := Transducers.markedSquare
assert_no_sorry «def:polyregular-functions#2»

/-- **Theorem `thm:polyregular-functions-are-continuous`** (continuity): `Transducers.polyregular_continuous`. -/
alias «thm:polyregular-functions-are-continuous» := Transducers.polyregular_continuous
assert_no_sorry «thm:polyregular-functions-are-continuous»

/-- **Theorem `thm:for-transducers-are-polyregular`** (polyregular = for-transducers): `Transducers.polyregular_iff_forTransducer`. -/
alias «thm:for-transducers-are-polyregular» := Transducers.polyregular_iff_forTransducer
assert_uses_sorry «thm:for-transducers-are-polyregular»

/-- **Definition `def:prenex-normal-form-for-transducers`** (prenex form): `Transducers.ForProg.PrenexForm`. -/
alias «def:prenex-normal-form-for-transducers» := Transducers.ForProg.PrenexForm
assert_no_sorry «def:prenex-normal-form-for-transducers»

/-- **Lemma `lemma:prenex-normal-form`** (prenex normal form): `Transducers.forTransducer_prenex`. -/
alias «lemma:prenex-normal-form» := Transducers.forTransducer_prenex
assert_uses_sorry «lemma:prenex-normal-form»

/-- **Lemma `lem:for-closed-under-composition`** (composition): `Transducers.forTransducer_comp`. -/
alias «lem:for-closed-under-composition» := Transducers.forTransducer_comp
assert_uses_sorry «lem:for-closed-under-composition»

/-- **Theorem `thm:pebble-are-continuous`** (continuity): `Transducers.pebble_continuous`. -/
alias «thm:pebble-are-continuous» := Transducers.pebble_continuous
assert_uses_sorry «thm:pebble-are-continuous»

/-- **Theorem `thm:pebble-are-for`** (pebble = for-transducers): `Transducers.pebble_iff_forTransducer`. -/
alias «thm:pebble-are-for» := Transducers.pebble_iff_forTransducer
assert_uses_sorry «thm:pebble-are-for»

/-
The exercises that carry a `\label` in the sources, from `EXERCISES.md`.
Exercises are not numbered results of the main text; the ones with no label in
the sources are listed in `EXERCISES.md` by chapter and position instead, and
are not aliased here.
-/

/-- **Exercise `exer:reverse-continuous`** (continuity of reversal): `Transducers.Exercises.reverse_continuous`. -/
alias «exer:reverse-continuous» := Transducers.Exercises.reverse_continuous
assert_no_sorry «exer:reverse-continuous»

/-- **Exercise `exer:duplication-continuous`** (continuity of duplication): `Transducers.Exercises.duplication_continuous`. -/
alias «exer:duplication-continuous» := Transducers.Exercises.duplication_continuous
assert_no_sorry «exer:duplication-continuous»

/-- **Exercise `exer:squaring-continuous`** (continuity of squaring): `Transducers.Exercises.squaring_continuous`. -/
alias «exer:squaring-continuous» := Transducers.Exercises.squaring_continuous
assert_no_sorry «exer:squaring-continuous»

/-- **Exercise `exer:factorial-continuous`** (continuity of the factorial function): `Transducers.Exercises.factorial_continuous`. -/
alias «exer:factorial-continuous» := Transducers.Exercises.factorial_continuous
assert_no_sorry «exer:factorial-continuous»

/-- **Exercise `exer:factorial-power-continuous`** (continuity of `w ↦ w^{g(|w|)!}`): `Transducers.Exercises.factorial_power_continuous`. -/
alias «exer:factorial-power-continuous» := Transducers.Exercises.factorial_power_continuous
assert_no_sorry «exer:factorial-power-continuous»

/-- **Exercise `ex:continuity-for-finite-images`** (finitely many output values): `Transducers.Exercises.continuous_iff_regular_fibers`. -/
alias «ex:continuity-for-finite-images» := Transducers.Exercises.continuous_iff_regular_fibers
assert_no_sorry «ex:continuity-for-finite-images»

/-- **Exercise `exer:finite-images-assumption-necessary`** (the assumption is necessary): `Transducers.Exercises.exists_regular_fibers_not_continuous`. -/
alias «exer:finite-images-assumption-necessary» :=
  Transducers.Exercises.exists_regular_fibers_not_continuous
assert_no_sorry «exer:finite-images-assumption-necessary»

/-- **Exercise `exer:middle-letter-not-continuous`** (the middle letter function): `Transducers.Exercises.middleLetter_not_continuous`. -/
alias «exer:middle-letter-not-continuous» := Transducers.Exercises.middleLetter_not_continuous
assert_no_sorry «exer:middle-letter-not-continuous»

/-- **Exercise `ex:distance`** (the distance on strings): `Transducers.Exercises.strDist`. -/
alias «ex:distance» := Transducers.Exercises.strDist
assert_no_sorry «ex:distance»

/-- **Exercise `ex:distance`** (it is a distance): `Transducers.Exercises.strDist_isMetric`. -/
alias «ex:distance#2» := Transducers.Exercises.strDist_isMetric
assert_no_sorry «ex:distance#2»

/-- **Exercise `ex:distance`** (it is even an ultrametric): `Transducers.Exercises.strDist_ultrametric`. -/
alias «ex:distance#3» := Transducers.Exercises.strDist_ultrametric
assert_no_sorry «ex:distance#3»

/-- **Exercise `ex:distance`** (the resulting metric space): `Transducers.Exercises.strMetric`. -/
alias «ex:distance#4» := Transducers.Exercises.strMetric
assert_no_sorry «ex:distance#4»

/-- **Exercise `exer:all-functions-continuous-for-metric`** (all functions are continuous): `Transducers.Exercises.strDist_all_continuous`. -/
alias «exer:all-functions-continuous-for-metric» := Transducers.Exercises.strDist_all_continuous
assert_no_sorry «exer:all-functions-continuous-for-metric»

/-- **Exercise `exer:continuous-iff-uniformly-continuous`** (continuity is uniform continuity): `Transducers.Exercises.continuous_iff_uniformContinuous`. -/
alias «exer:continuous-iff-uniformly-continuous» :=
  Transducers.Exercises.continuous_iff_uniformContinuous
assert_no_sorry «exer:continuous-iff-uniformly-continuous»

/-- **Exercise `exer:regular-languages-for-rational-relations`** (the domain of a rational relation): `Transducers.Exercises.rationalRel_domain_isRegular`. -/
alias «exer:regular-languages-for-rational-relations» :=
  Transducers.Exercises.rationalRel_domain_isRegular
assert_no_sorry «exer:regular-languages-for-rational-relations»

/-- **Exercise `exer:regular-languages-for-rational-relations`** (the range of a rational relation): `Transducers.Exercises.rationalRel_range_isRegular`. -/
alias «exer:regular-languages-for-rational-relations#2» :=
  Transducers.Exercises.rationalRel_range_isRegular
assert_no_sorry «exer:regular-languages-for-rational-relations#2»

/-- **Exercise `exer:non-regular-languages-for-rational-relations`** (the inputs with at most one output need not form a regular language): `Transducers.Exercises.exists_rationalRel_atMostOneOutput_not_isRegular`. -/
alias «exer:non-regular-languages-for-rational-relations» :=
  Transducers.Exercises.exists_rationalRel_atMostOneOutput_not_isRegular
assert_no_sorry «exer:non-regular-languages-for-rational-relations»

/-- **Exercise `exer:rational-relations-not-closed-under-intersection`** (rational relations are not closed under intersection): `Transducers.Exercises.exists_rationalRel_inter_not_rationalRel`. -/
alias «exer:rational-relations-not-closed-under-intersection» :=
  Transducers.Exercises.exists_rationalRel_inter_not_rationalRel
assert_no_sorry «exer:rational-relations-not-closed-under-intersection»

/-- **Exercise `exer:rational-relations-intersection-undecidable`** (nonemptiness of the intersection is undecidable): `Transducers.Exercises.rationalRel_intersection_undecidable`. -/
alias «exer:rational-relations-intersection-undecidable» :=
  Transducers.Exercises.rationalRel_intersection_undecidable
assert_no_sorry «exer:rational-relations-intersection-undecidable»

/-- **Exercise `exer:rational-output-size`** (finitely many outputs = affine bound on the output length): `Transducers.Exercises.rationalRel_finiteOutputs_iff_affine`. -/
alias «exer:rational-output-size» := Transducers.Exercises.rationalRel_finiteOutputs_iff_affine
assert_no_sorry «exer:rational-output-size»

/-- **Exercise `exer:examples-of-rational-fun`** (item (a), the input if its length is even): `Transducers.Exercises.isBimachine_isRationalFun_evenLength`. -/
alias «exer:examples-of-rational-fun» := Transducers.Exercises.isBimachine_isRationalFun_evenLength
assert_no_sorry «exer:examples-of-rational-fun»

/-- **Exercise `exer:examples-of-rational-fun`** (item (b), swap the first and the last letter): `Transducers.Exercises.isBimachine_isRationalFun_swapFirstLast`. -/
alias «exer:examples-of-rational-fun#2» :=
  Transducers.Exercises.isBimachine_isRationalFun_swapFirstLast
assert_no_sorry «exer:examples-of-rational-fun#2»

/-- **Exercise `exer:examples-of-rational-fun`** (item (c), the last `#` and what follows it): `Transducers.Exercises.isBimachine_isRationalFun_upToLastHash`. -/
alias «exer:examples-of-rational-fun#3» :=
  Transducers.Exercises.isBimachine_isRationalFun_upToLastHash
assert_no_sorry «exer:examples-of-rational-fun#3»

/-- **Exercise `exer:non-rational`** (item (a), the first half of the input): `Transducers.Exercises.not_isRationalFun_firstHalf`. -/
alias «exer:non-rational» := Transducers.Exercises.not_isRationalFun_firstHalf
assert_no_sorry «exer:non-rational»

/-- **Exercise `exer:non-rational`** (item (b), duplication): `Transducers.Exercises.not_isRationalFun_duplicate`. -/
alias «exer:non-rational#2» := Transducers.Exercises.not_isRationalFun_duplicate
assert_no_sorry «exer:non-rational#2»

/-- **Exercise `exer:decide-rational-colision`** (item (a), the collision problem for two rational functions is undecidable): `Transducers.Exercises.rationalFun_collision_undecidable`. -/
alias «exer:decide-rational-colision» := Transducers.Exercises.rationalFun_collision_undecidable
assert_no_sorry «exer:decide-rational-colision»

/-- **Exercise `exer:function-that-is-not-rational`** (not rational, yet rational after every rational function into a one-letter alphabet): `Transducers.Exercises.exists_not_isRationalFun_unary_compositions_rational`. -/
alias «exer:function-that-is-not-rational» :=
  Transducers.Exercises.exists_not_isRationalFun_unary_compositions_rational
assert_no_sorry «exer:function-that-is-not-rational»

/-- **Exercise `exer:some-ideals`** (first item, the functions with a range of size at most `k`): `Transducers.Exercises.isIdeal_rangeAtMost`. -/
alias «exer:some-ideals» := Transducers.Exercises.isIdeal_rangeAtMost
assert_no_sorry «exer:some-ideals»

/-- **Exercise `exer:some-ideals`** (second item, the functions with `O(n^k)` outputs): `Transducers.Exercises.isIdeal_outputsPoly`. -/
alias «exer:some-ideals#2» := Transducers.Exercises.isIdeal_outputsPoly
assert_no_sorry «exer:some-ideals#2»

/-- **Exercise `exer:finite-range-ideals`** (an ideal of functions with finite range is `RangeAtMost k` or `OutputsPoly 0`): `Transducers.Exercises.finite_range_ideal_classification`. -/
alias «exer:finite-range-ideals» := Transducers.Exercises.finite_range_ideal_classification
assert_no_sorry «exer:finite-range-ideals»

/-- **Exercise `exer:surjective-rational-function`** (a surjective rational function has a rational one-sided inverse): `Transducers.Exercises.exists_rationalFun_leftInverse`. -/
alias «exer:surjective-rational-function» := Transducers.Exercises.exists_rationalFun_leftInverse
assert_no_sorry «exer:surjective-rational-function»

/-- **Exercise `exer:two-letter-alphabet-suffices`** (a two-letter alphabet suffices for the prime regular functions): `Transducers.Exercises.isRegularFun_iff_compClosure2`. -/
alias «exer:two-letter-alphabet-suffices» := Transducers.Exercises.isRegularFun_iff_compClosure2
assert_no_sorry «exer:two-letter-alphabet-suffices»

/-- **Exercise `exer:mealy-as-restricted-mso-relabelling`** (Mealy machines are the restricted mso relabellings): `Transducers.Exercises.isMealy_iff_restrictedRelabelling`. -/
alias «exer:mealy-as-restricted-mso-relabelling» :=
  Transducers.Exercises.isMealy_iff_restrictedRelabelling
assert_no_sorry «exer:mealy-as-restricted-mso-relabelling»

/-
The theorem-like environments of the book that are not aliased
above, so that this file accounts for all of them:

* `def:rational-recognisable-subsets` (definition) -- not formalised (rational and recognisable subsets of a monoid, which the later sections do not use);
* `claim:bounded-extensions` (claim) -- not formalised (internal step of Theorem `thm:subsequential-functions`);
* `claim:computing-branching-part` (claim) -- not formalised (internal step of Theorem `thm:subsequential-functions`);
* `claim:offsets-are-regular` (claim) -- not formalised (internal step of Theorem `thm:subsequential-functions`);
* `claim:eliminating-negative-letters` (claim) -- not formalised (internal step of Theorem `thm:subsequential-functions`);
* `nolabel:conj-regular-via-weighted-automata` (conjecture) -- a conjecture of the book, not a result to formalise;
* `lem:compute-configuration-graph` (lemma) -- not formalised (the string encoding of the configuration graph, used only inside proofs of Part C);
* `lem:check-if-output-string-of-configuration-graph-belongs-to-L` (lemma) -- not formalised (the string encoding of the configuration graph, used only inside proofs of Part C);
* `lem:output-of-snake-graph-is-regular` (lemma) -- not formalised (the string encoding of the configuration graph, used only inside proofs of Part C);
* `nolabel:thm-fo-transduction-into-primes` (theorem) -- removed from the formalised theorems at the user's request; its statement is kept, commented out, in `PartC/MSOOpen.lean`;
* `lem:reachability-pebble-automaton` (lemma) -- not formalised (configuration encodings used inside proofs);
* `claim:reachability-basic-run` (claim) -- not formalised (configuration encodings used inside proofs);
* `lem:children-of-configuration-in-pebble-run` (lemma) -- not formalised (configuration encodings used inside proofs);
* `claim:from-configuration-to-child-configuration-graph` (claim) -- not formalised (configuration encodings used inside proofs);
* `claim:from-child-configuration-graph-to-children` (claim) -- not formalised (configuration encodings used inside proofs);
-/

end Transducers.Book
