/-
The label-indexed view of the formalisation.

The results of *Transducers* (M. Bojańczyk) are referred to throughout this
project by their LaTeX labels rather than by their numbers, which change
whenever the sources are edited (see `LABELS.md`).  This file makes that
correspondence part of the Lean development: for every formalised numbered
result, it declares an alias whose Lean name *is* the label of the result, so
the compiler checks that the declaration named in the documentation exists and
has the stated form.  The results themselves keep their descriptive Lean names;
nothing here is used in a proof.

Each alias is followed by a report of whether the result is proved outright:
`assert_no_sorry` fails if the declaration depends on `sorryAx`, or on any axiom
other than `propext`, `Classical.choice` and `Quot.sound`, and the statements
that are formalised but not yet proved carry `assert_uses_sorry` instead.  So
the status recorded in `THEOREMS.md` is checked here too, and so is the claim
made there that `#print axioms` on every formalised result of the book reports
only the three standard axioms.  At present every alias carries
`assert_no_sorry`: nothing that is formalised is left unproved.  The results
that are proved from an explicit hypothesis take that hypothesis as an argument
of the theorem, not as an axiom, so they pass this check as well.

Where a result of the book is formalised by several declarations, the first one
carries the label and the others carry the label followed by `#2`, `#3`, ....

This file is generated by `tools/gen_labels.py` from the status tables of
`THEOREMS.md`; edit those, not this file.  Its last section does the same for
the exercises of the book, whose status tables are in `EXERCISES.md`.
-/
import RequestProject.Common
import RequestProject.PartA
import RequestProject.PartB
import RequestProject.PartC
import RequestProject.PartD
import RequestProject.Exercises

namespace Transducers.Book

open Lean Elab Command in
/-- `assert_no_sorry foo` fails unless `foo` is proved without `sorry` and uses
no axiom beyond `propext`, `Classical.choice` and `Quot.sound`. -/
elab "assert_no_sorry " id:ident : command => do
  let n ← liftCoreM <| realizeGlobalConstNoOverload id
  let axs ← liftCoreM <| Lean.collectAxioms n
  if axs.contains ``sorryAx then
    throwError "{n} depends on sorryAx"
  let extra := axs.filter fun a =>
    a != ``propext && a != ``Classical.choice && a != ``Quot.sound
  unless extra.isEmpty do
    throwError "{n} depends on {extra.toList}, beyond propext, Classical.choice, Quot.sound"

open Lean Elab Command in
/-- `assert_uses_sorry foo` fails unless `foo` still depends on `sorry`.  It
marks the statements of the book that are formalised but not proved yet. -/
elab "assert_uses_sorry " id:ident : command => do
  let n ← liftCoreM <| realizeGlobalConstNoOverload id
  let axs ← liftCoreM <| Lean.collectAxioms n
  if !axs.contains ``sorryAx then
    throwError "{n} does not depend on sorryAx"


/-- **Definition `def:continuity`** (continuity): `Transducers.Continuous`. -/
alias «def:continuity» := Transducers.Continuous
assert_no_sorry «def:continuity»

/-- **Definition `def:mealy-machine`** (Mealy machine): `Transducers.Mealy`. -/
alias «def:mealy-machine» := Transducers.Mealy
assert_no_sorry «def:mealy-machine»

/-- **Definition `def:mealy-machine`** (Mealy machine): `Transducers.Mealy.eval`. -/
alias «def:mealy-machine#2» := Transducers.Mealy.eval
assert_no_sorry «def:mealy-machine#2»

/-- **Definition `def:mealy-machine`** (Mealy machine): `Transducers.IsMealy`. -/
alias «def:mealy-machine#3» := Transducers.IsMealy
assert_no_sorry «def:mealy-machine#3»

/-- **Theorem `thm:equivalence-decidable-mealy`** (decidable equivalence): `Transducers.mealy_equiv_iff_bounded`. -/
alias «thm:equivalence-decidable-mealy» := Transducers.mealy_equiv_iff_bounded
assert_no_sorry «thm:equivalence-decidable-mealy»

/-- **Theorem `thm:composition-mealy`** (composition): `Transducers.mealy_comp`. -/
alias «thm:composition-mealy» := Transducers.mealy_comp
assert_no_sorry «thm:composition-mealy»

/-- **Theorem `thm:continuity-mealy`** (continuity): `Transducers.mealy_continuous`. -/
alias «thm:continuity-mealy» := Transducers.mealy_continuous
assert_no_sorry «thm:continuity-mealy»

/-- **Definition `def:prime-mealy-machines`** (prime Mealy machines): `Transducers.Mealy.Reversible`. -/
alias «def:prime-mealy-machines» := Transducers.Mealy.Reversible
assert_no_sorry «def:prime-mealy-machines»

/-- **Definition `def:prime-mealy-machines`** (prime Mealy machines): `Transducers.Mealy.FlipFlop`. -/
alias «def:prime-mealy-machines#2» := Transducers.Mealy.FlipFlop
assert_no_sorry «def:prime-mealy-machines#2»

/-- **Definition `def:prime-mealy-machines`** (prime Mealy machines): `Transducers.PrimeMealyFam`. -/
alias «def:prime-mealy-machines#3» := Transducers.PrimeMealyFam
assert_no_sorry «def:prime-mealy-machines#3»

/-- **Theorem `thm:krohn-rhodes`** (Krohn–Rhodes): `Transducers.krohn_rhodes`. -/
alias «thm:krohn-rhodes» := Transducers.krohn_rhodes
assert_no_sorry «thm:krohn-rhodes»

/-- **Definition `def:map-lifting`** (map lifting): `Transducers.mapLift`. -/
alias «def:map-lifting» := Transducers.mapLift
assert_no_sorry «def:map-lifting»

/-- **Lemma `lem:map-lifting-decomposition-mealy`** (map lifting of a decomposition): `Transducers.mapLift_prime_decomposition`. -/
alias «lem:map-lifting-decomposition-mealy» := Transducers.mapLift_prime_decomposition
assert_no_sorry «lem:map-lifting-decomposition-mealy»

/-- **Lemma `lem:Mealy-map-lifting`** (state transformation transducer): `Transducers.stateTransTransducer_prime_decomposition`. -/
alias «lem:Mealy-map-lifting» := Transducers.stateTransTransducer_prime_decomposition
assert_no_sorry «lem:Mealy-map-lifting»

/-- **Lemma `lem:reversible-composition`** (reversible machines compose): `Transducers.reversible_comp`. -/
alias «lem:reversible-composition» := Transducers.reversible_comp
assert_no_sorry «lem:reversible-composition»

/-- **Definition `def:aperiodic-mealy`** (aperiodic): `Transducers.Aperiodic`. -/
alias «def:aperiodic-mealy» := Transducers.Aperiodic
assert_no_sorry «def:aperiodic-mealy»

/-- **Theorem `thm:aperiodic-mealy`** (aperiodic = flip-flops): `Transducers.aperiodic_iff_flipflop_composition`. -/
alias «thm:aperiodic-mealy» := Transducers.aperiodic_iff_flipflop_composition
assert_no_sorry «thm:aperiodic-mealy»

/-- **Claim `claim:aperiodic-pumping`** (pumping form of aperiodicity): `Transducers.aperiodic_iff_pumping`. -/
alias «claim:aperiodic-pumping» := Transducers.aperiodic_iff_pumping
assert_no_sorry «claim:aperiodic-pumping»

/-- **Lemma `lemma:derivatives`** (Myhill–Nerode): `Transducers.myhill_nerode_mealy`. -/
alias «lemma:derivatives» := Transducers.myhill_nerode_mealy
assert_no_sorry «lemma:derivatives»

/-- **Lemma `lem:aperiodicity-minimal-machine`** (condition (*)): `Transducers.aperiodic_iff_transStabilises`. -/
alias «lem:aperiodicity-minimal-machine» := Transducers.aperiodic_iff_transStabilises
assert_no_sorry «lem:aperiodicity-minimal-machine»

/-- **Definition `def:nfa-with-output`** (nfa with output): `Transducers.NFAO`. -/
alias «def:nfa-with-output» := Transducers.NFAO
assert_no_sorry «def:nfa-with-output»

/-- **Definition `def:nfa-with-output`** (nfa with output): `Transducers.LabAut`. -/
alias «def:nfa-with-output#2» := Transducers.LabAut
assert_no_sorry «def:nfa-with-output#2»

/-- **Definition `def:rational-relation`** (rational relation): `Transducers.IsRationalRel`. -/
alias «def:rational-relation» := Transducers.IsRationalRel
assert_no_sorry «def:rational-relation»

/-- **Theorem `thm:composition-rational-relations`** (composition): `Transducers.rationalRel_comp`. -/
alias «thm:composition-rational-relations» := Transducers.rationalRel_comp
assert_no_sorry «thm:composition-rational-relations»

/-- **Theorem `thm:continuity-rational-relations`** (continuity): `Transducers.rationalRel_continuous`. -/
alias «thm:continuity-rational-relations» := Transducers.rationalRel_continuous
assert_no_sorry «thm:continuity-rational-relations»

/-- **Theorem `thm:undecidable-equivalence-rational-relations`** (undecidable equivalence): `Transducers.rationalRel_equivalence_undecidable`. -/
alias «thm:undecidable-equivalence-rational-relations» := Transducers.rationalRel_equivalence_undecidable
assert_no_sorry «thm:undecidable-equivalence-rational-relations»

/-- **Claim `claim:homomorphism-complement-rational`** (complement of a homomorphism): `Transducers.hom_complement_rational`. -/
alias «claim:homomorphism-complement-rational» := Transducers.hom_complement_rational
assert_no_sorry «claim:homomorphism-complement-rational»

/-- **Definition `def:rational-function`** (rational function): `Transducers.IsRationalFun`. -/
alias «def:rational-function» := Transducers.IsRationalFun
assert_no_sorry «def:rational-function»

/-- **Definition `def:bimachine`** (bimachine): `Transducers.Bimachine`. -/
alias «def:bimachine» := Transducers.Bimachine
assert_no_sorry «def:bimachine»

/-- **Definition `def:bimachine`** (bimachine): `Transducers.IsBimachine`. -/
alias «def:bimachine#2» := Transducers.IsBimachine
assert_no_sorry «def:bimachine#2»

/-- **Theorem `thm:bimachines`** (rational = unambiguous = bimachine): `Transducers.rational_iff_unambiguous_iff_bimachine`. -/
alias «thm:bimachines» := Transducers.rational_iff_unambiguous_iff_bimachine
assert_no_sorry «thm:bimachines»

/-- **Lemma `lemma:eliminate-epsilon-transitions`** (elimination of ε-transitions): `Transducers.epsilon_elimination`. -/
alias «lemma:eliminate-epsilon-transitions» := Transducers.epsilon_elimination
assert_no_sorry «lemma:eliminate-epsilon-transitions»

/-- **Lemma `lem:uniformisation`** (uniformisation): `Transducers.uniformisation`. -/
alias «lem:uniformisation» := Transducers.uniformisation
assert_no_sorry «lem:uniformisation»

/-- **Theorem `thm:rational-primes`** (decomposition into primes): `Transducers.rational_iff_prime_composition`. -/
alias «thm:rational-primes» := Transducers.rational_iff_prime_composition
assert_no_sorry «thm:rational-primes»

/-- **Theorem `thm:rational-is-mealy-characterisation`** (Mealy machines inside rational functions): `Transducers.rational_isMealy_iff`. -/
alias «thm:rational-is-mealy-characterisation» := Transducers.rational_isMealy_iff
assert_no_sorry «thm:rational-is-mealy-characterisation»

/-- **Definition `def:semiring`** (semiring): `Semiring`.  Not a numbered result of its own here: Mathlib's `Semiring`. -/
alias «def:semiring» := Semiring
assert_no_sorry «def:semiring»

/-- **Definition `def:weighted-automaton`** (weighted automaton): `Transducers.LabAut.wEval`. -/
alias «def:weighted-automaton» := Transducers.LabAut.wEval
assert_no_sorry «def:weighted-automaton»

/-- **Definition `def:weighted-automaton`** (weighted automaton): `Transducers.IsWeighted`. -/
alias «def:weighted-automaton#2» := Transducers.IsWeighted
assert_no_sorry «def:weighted-automaton#2»

/-- **Theorem `thm:equivalence-weighted-automata`** (equivalence over ℚ): `Transducers.weighted_equivalence_decidable`. -/
alias «thm:equivalence-weighted-automata» := Transducers.weighted_equivalence_decidable
assert_no_sorry «thm:equivalence-weighted-automata»

/-- **Theorem `thm:equivalence-rational-functions`** (equivalence of rational functions): `Transducers.rationalFun_equivalence_decidable`. -/
alias «thm:equivalence-rational-functions» := Transducers.rationalFun_equivalence_decidable
assert_no_sorry «thm:equivalence-rational-functions»

/-- **Lemma `lem:closure-weighted-automata-precomposition`** (pre-composition): `Transducers.weighted_precomp_rational`. -/
alias «lem:closure-weighted-automata-precomposition» := Transducers.weighted_precomp_rational
assert_no_sorry «lem:closure-weighted-automata-precomposition»

/-- **Theorem `thm:characterisation-rational-functions-weighted-automata`** (characterisation of rationality): `Transducers.rational_iff_weighted_precomp`. -/
alias «thm:characterisation-rational-functions-weighted-automata» := Transducers.rational_iff_weighted_precomp
assert_no_sorry «thm:characterisation-rational-functions-weighted-automata»

/-- **Theorem `thm:zeroness-weighted-automata`** (zeroness): `Transducers.weighted_zeroness_decidable`. -/
alias «thm:zeroness-weighted-automata» := Transducers.weighted_zeroness_decidable
assert_no_sorry «thm:zeroness-weighted-automata»

/-- **Theorem `thm:mealy-machine-independent`** (characterisation of Mealy machines): `Transducers.isMealy_iff`. -/
alias «thm:mealy-machine-independent» := Transducers.isMealy_iff
assert_no_sorry «thm:mealy-machine-independent»

/-- **Theorem `thm:decide-if-mealy`** (deciding the Mealy fragment): `Transducers.rationalFun_isMealy_decidable`. -/
alias «thm:decide-if-mealy» := Transducers.rationalFun_isMealy_decidable
assert_no_sorry «thm:decide-if-mealy»

/-- **Lemma `lem:decide-if-length-preserving`** (deciding length preservation): `Transducers.rationalFun_lengthPreserving_decidable`. -/
alias «lem:decide-if-length-preserving» := Transducers.rationalFun_lengthPreserving_decidable
assert_no_sorry «lem:decide-if-length-preserving»

/-- **Claim `claim:typing-length-preserving`** (typings): `Transducers.lengthPreserving_iff_typing`. -/
alias «claim:typing-length-preserving» := Transducers.lengthPreserving_iff_typing
assert_no_sorry «claim:typing-length-preserving»

/-- **Lemma `lem:characterisation-length-preserving`** (length-preserving normal form): `Transducers.lengthPreserving_rational_normal_form`. -/
alias «lem:characterisation-length-preserving» := Transducers.lengthPreserving_rational_normal_form
assert_no_sorry «lem:characterisation-length-preserving»

/-- **Theorem `thm:sequential-function-independent`** (sequential functions): `Transducers.isSequential_iff`. -/
alias «thm:sequential-function-independent» := Transducers.isSequential_iff
assert_no_sorry «thm:sequential-function-independent»

/-- **Definition `def:left-distance`** (left distance): `Transducers.leftDist`. -/
alias «def:left-distance» := Transducers.leftDist
assert_no_sorry «def:left-distance»

/-- **Theorem `thm:subsequential-functions`** (subsequential functions): `Transducers.isSubsequential_iff`. -/
alias «thm:subsequential-functions» := Transducers.isSubsequential_iff
assert_no_sorry «thm:subsequential-functions»

/-- **Claim `claim:bounded-extensions`** (a short extension into the domain suffices):
`Transducers.Subseq.delay_bound`.  The proof of Theorem `thm:subsequential-functions`
reorganises the book's four claims, so this is not a literal rendering: `delay_bound` is the
bound `M0` on the length of the branching part, i.e. the constant `K` that the book extracts
from this claim.  The claim itself, in the book's words, is
`Transducers.Subseq.exists_short_extension`. -/
alias «claim:bounded-extensions» := Transducers.Subseq.delay_bound
assert_no_sorry «claim:bounded-extensions»

/-- **Claim `claim:bounded-extensions`** (a short extension into the domain suffices):
`Transducers.Subseq.exists_short_extension`, the literal rendering. -/
alias «claim:bounded-extensions#2» := Transducers.Subseq.exists_short_extension
assert_no_sorry «claim:bounded-extensions#2»

/-- **Claim `claim:computing-branching-part`** (the branching part is computed by an automaton):
`Transducers.Subseq.key_drop`.  Phrased through Myhill-Nerode states rather than through regular
languages: the branching part of a string is determined by its state. -/
alias «claim:computing-branching-part» := Transducers.Subseq.key_drop
assert_no_sorry «claim:computing-branching-part»

/-- **Claim `claim:offsets-are-regular`** (the offsets are computed by an automaton):
`Transducers.Subseq.incr_congr`.  Phrased through Myhill-Nerode states rather than through
regular languages: the offset at a letter is determined by the state. -/
alias «claim:offsets-are-regular» := Transducers.Subseq.incr_congr
assert_no_sorry «claim:offsets-are-regular»

/-- **Claim `claim:eliminating-negative-letters`** (elimination of the negative letters):
`Transducers.Subseq.exists_deletion_bound`.  The free group is not used: instead of reducing a
word over `B ∪ B⁻¹`, the transducer emits the non-branching part with a bounded delay, and what
makes the delay bounded is that extending the input never shortens the non-branching part by
more than a fixed constant, which is this lemma. -/
alias «claim:eliminating-negative-letters» := Transducers.Subseq.exists_deletion_bound
assert_no_sorry «claim:eliminating-negative-letters»

/-- **Theorem `thm:machine-independent-rational-functions`** (rational functions): `Transducers.isRationalFun_iff`. -/
alias «thm:machine-independent-rational-functions» := Transducers.isRationalFun_iff
assert_no_sorry «thm:machine-independent-rational-functions»

/-- **Definition `def:regular-functions`** (regular functions): `Transducers.IsRegularFun`. -/
alias «def:regular-functions» := Transducers.IsRegularFun
assert_no_sorry «def:regular-functions»

/-- **Definition `def:regular-functions`** (regular functions): `Transducers.RegularFam`. -/
alias «def:regular-functions#2» := Transducers.RegularFam
assert_no_sorry «def:regular-functions#2»

/-- **Theorem `thm:regular-functions-are-continuous-and-closed-under-composition`** (continuity, composition): `Transducers.regular_continuous`. -/
alias «thm:regular-functions-are-continuous-and-closed-under-composition» := Transducers.regular_continuous
assert_no_sorry «thm:regular-functions-are-continuous-and-closed-under-composition»

/-- **Theorem `thm:regular-functions-are-continuous-and-closed-under-composition`** (continuity, composition): `Transducers.regular_comp`. -/
alias «thm:regular-functions-are-continuous-and-closed-under-composition#2» := Transducers.regular_comp
assert_no_sorry «thm:regular-functions-are-continuous-and-closed-under-composition#2»

/-- **Lemma `lem:reversal-duplication-continuous`** (reversal, duplication): `Transducers.reverse_duplicate_continuous`. -/
alias «lem:reversal-duplication-continuous» := Transducers.reverse_duplicate_continuous
assert_no_sorry «lem:reversal-duplication-continuous»

/-- **Lemma `lem:map-lifting-continuous`** (map lifting): `Transducers.mapLift_continuous`. -/
alias «lem:map-lifting-continuous» := Transducers.mapLift_continuous
assert_no_sorry «lem:map-lifting-continuous»

/-- **Theorem `thm:decidable-equivalence-regular`** (decidable equivalence): `Transducers.regular_equivalence_decidable`. -/
alias «thm:decidable-equivalence-regular» := Transducers.regular_equivalence_decidable
assert_no_sorry «thm:decidable-equivalence-regular»

/-- **Definition `def:two-way-transducer`** (two-way transducer): `Transducers.TwoWay`. -/
alias «def:two-way-transducer» := Transducers.TwoWay
assert_no_sorry «def:two-way-transducer»

/-- **Definition `def:two-way-transducer`** (two-way transducer): `Transducers.IsTwoWay`. -/
alias «def:two-way-transducer#2» := Transducers.IsTwoWay
assert_no_sorry «def:two-way-transducer#2»

/-- **Theorem `thm:continuity-2dfas`** (continuity): `Transducers.twoWay_continuous`. -/
alias «thm:continuity-2dfas» := Transducers.twoWay_continuous
assert_no_sorry «thm:continuity-2dfas»

/-- **Lemma `lem:compute-configuration-graph`** (computing the configuration graph): `Transducers.twoWay_isRationalFun_enc`, the function taking an input string to the string representation of its reachable configuration graph over the alphabet `Transducers.CLet`. -/
alias «lem:compute-configuration-graph» := Transducers.twoWay_isRationalFun_enc
assert_no_sorry «lem:compute-configuration-graph»

/-- **Lemma `lem:compute-configuration-graph`** (computing the configuration graph): `Transducers.twoWay_encLang_isRegular`, the main observation of its proof -- the strings that represent a reachable configuration graph form a regular language. -/
alias «lem:compute-configuration-graph#2» := Transducers.twoWay_encLang_isRegular
assert_no_sorry «lem:compute-configuration-graph#2»

/-- **Lemma `lem:check-if-output-string-of-configuration-graph-belongs-to-L`** (output string of the configuration graph in `L`): `Transducers.twoWay_encOutputLang_isRegular`, for a transducer that computes a total function, which the statement takes as an explicit hypothesis. -/
alias «lem:check-if-output-string-of-configuration-graph-belongs-to-L» := Transducers.twoWay_encOutputLang_isRegular
assert_no_sorry «lem:check-if-output-string-of-configuration-graph-belongs-to-L»

/-- **Theorem `thm:composition-of-two-way-transducers`** (composition): `Transducers.twoWay_comp`. -/
alias «thm:composition-of-two-way-transducers» := Transducers.twoWay_comp
assert_no_sorry «thm:composition-of-two-way-transducers»

/-- **Lemma `lem:2dfa-precomposition-with-mealy`** (pre-composition with Mealy machines): `Transducers.twoWay_precomp_mealy`. -/
alias «lem:2dfa-precomposition-with-mealy» := Transducers.twoWay_precomp_mealy
assert_no_sorry «lem:2dfa-precomposition-with-mealy»

/-- **Corollary `cor:2dfa-closure-under-composition`** (pre-composition with rational functions): `Transducers.twoWay_precomp_rational`. -/
alias «cor:2dfa-closure-under-composition» := Transducers.twoWay_precomp_rational
assert_no_sorry «cor:2dfa-closure-under-composition»

/-- **Corollary `cor:2dfa-computes-all-regular-functions`** (regular ⊆ two-way): `Transducers.regularFun_isTwoWay`. -/
alias «cor:2dfa-computes-all-regular-functions» := Transducers.regularFun_isTwoWay
assert_no_sorry «cor:2dfa-computes-all-regular-functions»

/-- **Corollary `cor:2dfa-computes-all-regular-functions`** (regular ⊆ two-way): `Transducers.isTwoWay_of_isRegularFun`. -/
alias «cor:2dfa-computes-all-regular-functions#2» := Transducers.isTwoWay_of_isRegularFun
assert_no_sorry «cor:2dfa-computes-all-regular-functions#2»

/-- **Theorem `thm:2dfa-decomposition-into-primes`** (two-way = regular): `Transducers.twoWay_iff_regular`. -/
alias «thm:2dfa-decomposition-into-primes» := Transducers.twoWay_iff_regular
assert_no_sorry «thm:2dfa-decomposition-into-primes»

/-- **Theorem `thm:2dfa-decomposition-into-primes`** (two-way = regular): `Transducers.twoWay_isRegular`. -/
alias «thm:2dfa-decomposition-into-primes#2» := Transducers.twoWay_isRegular
assert_no_sorry «thm:2dfa-decomposition-into-primes#2»

/-- **Lemma `lem:regular-closure-properties`** (closure properties): `Transducers.regular_closure_properties`. -/
alias «lem:regular-closure-properties» := Transducers.regular_closure_properties
assert_no_sorry «lem:regular-closure-properties»

/-- **Claim `claim:conditional`** (disjoint sums): `Transducers.sum_of_regular`. -/
alias «claim:conditional» := Transducers.sum_of_regular
assert_no_sorry «claim:conditional»

/-- **Lemma `lem:output-of-snake-graph-is-regular`** (the output of a snake graph is regular):
`Transducers.SnakeGraph.snakeOut_isRegular`.  Stated as in the book, over the alphabet
`Transducers.SnakeLetter Q B` of snake letters, and for every `k : ℕ` rather than for
`k ∈ {1, …, |Q|}`. -/
alias «lem:output-of-snake-graph-is-regular» := Transducers.SnakeGraph.snakeOut_isRegular
assert_no_sorry «lem:output-of-snake-graph-is-regular»

/-- **Lemma `lem:output-of-snake-graph-is-regular`** (the output of a snake graph is regular):
`Transducers.boundedWidth_isRegular`.  The general form the book's statement is proved from:
the width-`k` output function `TwoWay.widthOut` of a two-way transducer, for every `k : ℕ`. -/
alias «lem:output-of-snake-graph-is-regular#2» := Transducers.boundedWidth_isRegular
assert_no_sorry «lem:output-of-snake-graph-is-regular#2»

/-- **Definition `def:sst`** (sst): `Transducers.SST`. -/
alias «def:sst» := Transducers.SST
assert_no_sorry «def:sst»

/-- **Definition `def:sst`** (sst): `Transducers.IsSST`. -/
alias «def:sst#2» := Transducers.IsSST
assert_no_sorry «def:sst#2»

/-- **Theorem `theorem:sst-two-way-equivalence`** (sst = regular): `Transducers.sst_iff_regular`. -/
alias «theorem:sst-two-way-equivalence» := Transducers.sst_iff_regular
assert_no_sorry «theorem:sst-two-way-equivalence»

/-- **Theorem `thm:mso-logic-languages`** (mso = regular languages): `Transducers.regular_iff_msoDefinable`. -/
alias «thm:mso-logic-languages» := Transducers.regular_iff_msoDefinable
assert_no_sorry «thm:mso-logic-languages»

/-- **Lemma `lem:mso-free-variables`** (formulas with free variables): `Transducers.mso_annotated_regular`. -/
alias «lem:mso-free-variables» := Transducers.mso_annotated_regular
assert_no_sorry «lem:mso-free-variables»

/-- **Definition `def:mso-relabeling`** (mso relabelling): `Transducers.MSORelabelling`. -/
alias «def:mso-relabeling» := Transducers.MSORelabelling
assert_no_sorry «def:mso-relabeling»

/-- **Definition `def:mso-relabeling`** (mso relabelling): `Transducers.IsMSORelabelling`. -/
alias «def:mso-relabeling#2» := Transducers.IsMSORelabelling
assert_no_sorry «def:mso-relabeling#2»

/-- **Theorem `thm:logic-rational-functions`** (rational = mso relabelling): `Transducers.rational_iff_msoRelabelling`. -/
alias «thm:logic-rational-functions» := Transducers.rational_iff_msoRelabelling
assert_no_sorry «thm:logic-rational-functions»

/-- **Claim `claim:transition-formula`** (transition formula): `Transducers.RatRelab.exists_form`.  Not a numbered result of its own here: an internal step of Theorem `thm:logic-rational-functions`, stated for the index of a bimachine. -/
alias «claim:transition-formula» := Transducers.RatRelab.exists_form
assert_no_sorry «claim:transition-formula»

/-- **Claim `claim:mso-annotation-regular`** (annotated relabellings): `Transducers.msoRelabelling_annotation_regular`. -/
alias «claim:mso-annotation-regular» := Transducers.msoRelabelling_annotation_regular
assert_no_sorry «claim:mso-annotation-regular»

/-- **Definition `def:mso-transduction`** (mso transduction): `Transducers.MSOTransduction`. -/
alias «def:mso-transduction» := Transducers.MSOTransduction
assert_no_sorry «def:mso-transduction»

/-- **Definition `def:mso-transduction`** (mso transduction): `Transducers.IsMSOTransduction`. -/
alias «def:mso-transduction#2» := Transducers.IsMSOTransduction
assert_no_sorry «def:mso-transduction#2»

/-- **Theorem `thm:logic-regular-functions`** (mso transductions = regular): `Transducers.msoTransduction_iff_regular`. -/
alias «thm:logic-regular-functions» := Transducers.msoTransduction_iff_regular
assert_no_sorry «thm:logic-regular-functions»

/-- **Lemma `lem:logic-reduction-to-type-n`** (reduction to type n): `Transducers.MSOTransduction.exists_norm`.  Not a numbered result of its own here: an internal step of Theorem `thm:logic-regular-functions`: the normalisation of the type. -/
alias «lem:logic-reduction-to-type-n» := Transducers.MSOTransduction.exists_norm
assert_no_sorry «lem:logic-reduction-to-type-n»

/-- **Lemma `lem:logic-precomputation`** (formulas via rational functions): `Transducers.mso_formulas_via_rational`. -/
alias «lem:logic-precomputation» := Transducers.mso_formulas_via_rational
assert_no_sorry «lem:logic-precomputation»

/-- **Theorem `thm:logic-aperiodic`** (first-order = aperiodic): `Transducers.foDefinable_iff_aperiodic_dfa`. -/
alias «thm:logic-aperiodic» := Transducers.foDefinable_iff_aperiodic_dfa
assert_no_sorry «thm:logic-aperiodic»

/-- **Definition `def:k-types`** (k-types): `Transducers.tp`. -/
alias «def:k-types» := Transducers.tp
assert_no_sorry «def:k-types»

/-- **Lemma `lem:k-types-fo-equivalence`** (types and formulas): `Transducers.tp_eq_iff_fo_equiv`. -/
alias «lem:k-types-fo-equivalence» := Transducers.tp_eq_iff_fo_equiv
assert_no_sorry «lem:k-types-fo-equivalence»

/-- **Claim `claim:fo-composition-quantifier-rank`** (the type of a tuple): `Transducers.sat_iff_of_kEquiv`.  Not a numbered result of its own here: an internal step of Lemma `lem:k-types-fo-equivalence`. -/
alias «claim:fo-composition-quantifier-rank» := Transducers.sat_iff_of_kEquiv
assert_no_sorry «claim:fo-composition-quantifier-rank»

/-- **Lemma `lem:k-types-properties`** (properties of types): `Transducers.tp_properties`. -/
alias «lem:k-types-properties» := Transducers.tp_properties
assert_no_sorry «lem:k-types-properties»

/-- **Theorem `thm:fo-rational-functions`** (first-order relabellings): `Transducers.foRelabelling_iff_aperiodicBimachine`. -/
alias «thm:fo-rational-functions» := Transducers.foRelabelling_iff_aperiodicBimachine
assert_no_sorry «thm:fo-rational-functions»

/-- **Definition `def:polyregular-functions`** (polyregular functions): `Transducers.IsPolyregular`. -/
alias «def:polyregular-functions» := Transducers.IsPolyregular
assert_no_sorry «def:polyregular-functions»

/-- **Definition `def:polyregular-functions`** (polyregular functions): `Transducers.markedSquare`. -/
alias «def:polyregular-functions#2» := Transducers.markedSquare
assert_no_sorry «def:polyregular-functions#2»

/-- **Theorem `thm:polyregular-functions-are-continuous`** (continuity): `Transducers.polyregular_continuous`. -/
alias «thm:polyregular-functions-are-continuous» := Transducers.polyregular_continuous
assert_no_sorry «thm:polyregular-functions-are-continuous»

/-- **Theorem `thm:for-transducers-are-polyregular`** (polyregular = for-transducers): `Transducers.polyregular_iff_forTransducer`. -/
alias «thm:for-transducers-are-polyregular» := Transducers.polyregular_iff_forTransducer
assert_no_sorry «thm:for-transducers-are-polyregular»

/-- **Definition `def:prenex-normal-form-for-transducers`** (prenex form): `Transducers.ForProg.PrenexForm`. -/
alias «def:prenex-normal-form-for-transducers» := Transducers.ForProg.PrenexForm
assert_no_sorry «def:prenex-normal-form-for-transducers»

/-- **Lemma `lemma:prenex-normal-form`** (prenex normal form): `Transducers.forTransducer_prenex`. -/
alias «lemma:prenex-normal-form» := Transducers.forTransducer_prenex
assert_no_sorry «lemma:prenex-normal-form»

/-- **Lemma `lem:for-closed-under-composition`** (composition): `Transducers.forTransducer_comp`. -/
alias «lem:for-closed-under-composition» := Transducers.forTransducer_comp
assert_no_sorry «lem:for-closed-under-composition»

/-- **Theorem `thm:pebble-are-continuous`** (continuity): `Transducers.pebble_continuous`. -/
alias «thm:pebble-are-continuous» := Transducers.pebble_continuous
assert_no_sorry «thm:pebble-are-continuous»

/-- **Lemma `lem:reachability-pebble-automaton`** (reachability of configurations): `Transducers.reachability_pebble_automaton`.  The book's mso formula with two free variables of the type of configurations is rendered as a regular language of encodings of pairs of configurations; see the header of `RequestProject/PartD/PebReach.lean`. -/
alias «lem:reachability-pebble-automaton» := Transducers.reachability_pebble_automaton
assert_no_sorry «lem:reachability-pebble-automaton»

/-- **Claim `claim:reachability-basic-run`** (balanced runs): `Transducers.reachability_basic_run`. -/
alias «claim:reachability-basic-run» := Transducers.reachability_basic_run
assert_no_sorry «claim:reachability-basic-run»

/-- **Theorem `thm:pebble-are-for`** (pebble = for-transducers): `Transducers.pebble_iff_forTransducer`. -/
alias «thm:pebble-are-for» := Transducers.pebble_iff_forTransducer
assert_no_sorry «thm:pebble-are-for»

/-- **Lemma `lem:children-of-configuration-in-pebble-run`** (the children of a configuration): `Transducers.children_of_configuration_in_pebble_run`. -/
alias «lem:children-of-configuration-in-pebble-run» := Transducers.children_of_configuration_in_pebble_run
assert_no_sorry «lem:children-of-configuration-in-pebble-run»

/-- **Claim `claim:from-configuration-to-child-configuration-graph`** (configuration to child configuration graph): `Transducers.from_configuration_to_child_configuration_graph`. -/
alias «claim:from-configuration-to-child-configuration-graph» := Transducers.from_configuration_to_child_configuration_graph
assert_no_sorry «claim:from-configuration-to-child-configuration-graph»

/-- **Claim `claim:from-child-configuration-graph-to-children`** (child configuration graph to children): `Transducers.from_child_configuration_graph_to_children`. -/
alias «claim:from-child-configuration-graph-to-children» := Transducers.from_child_configuration_graph_to_children
assert_no_sorry «claim:from-child-configuration-graph-to-children»

/-! ## Exercises

The exercises of the book are not numbered results, so they are indexed in
`EXERCISES.md` rather than in `THEOREMS.md`; the aliases below follow the same
convention as the ones above.  Only the exercises that carry a `\label` in the
sources appear here, and every exercise of Part A does.  Where an exercise is
formalised by several declarations, the first one carries the label and the
others carry the label followed by `#2`. -/

/-- **Exercise `exer:letter-to-letter-not-mealy`** (a continuous letter-to-letter function that is not Mealy): `Transducers.reverse_continuous_lengthPreserving_not_mealy`. -/
alias «exer:letter-to-letter-not-mealy» := Transducers.reverse_continuous_lengthPreserving_not_mealy
assert_no_sorry «exer:letter-to-letter-not-mealy»

/-- **Exercise `exer:composition-needs-many-states`** (exponentially many states): `Transducers.mealy_composition_state_blowup`. -/
alias «exer:composition-needs-many-states» := Transducers.mealy_composition_state_blowup
assert_no_sorry «exer:composition-needs-many-states»

/-- **Exercise `exer:invertible`** (invertibility is decidable): `Transducers.mealy_invertible_iff`. -/
alias «exer:invertible» := Transducers.mealy_invertible_iff
assert_no_sorry «exer:invertible»

/-- **Exercise `exer:invertible`** (invertibility is decidable): `Transducers.decidableInvertible`. -/
alias «exer:invertible#2» := Transducers.decidableInvertible
assert_no_sorry «exer:invertible#2»

/-- **Exercise `exer:invertible-mealy-group`** (an infinite generated subgroup): `Transducers.exists_invertible_mealy_infinite_order`. -/
alias «exer:invertible-mealy-group» := Transducers.exists_invertible_mealy_infinite_order
assert_no_sorry «exer:invertible-mealy-group»

/-- **Exercise `exer:polynomial-image-growth-decidable`** (polynomial growth of the image): `Transducers.mealy_imageGrowth_polyBounded_iff`. -/
alias «exer:polynomial-image-growth-decidable» := Transducers.mealy_imageGrowth_polyBounded_iff
assert_no_sorry «exer:polynomial-image-growth-decidable»

/-- **Exercise `exer:polynomial-image-growth-decidable`** (polynomial growth of the image): `Transducers.decidableImageGrowthPolyBounded`. -/
alias «exer:polynomial-image-growth-decidable#2» := Transducers.decidableImageGrowthPolyBounded
assert_no_sorry «exer:polynomial-image-growth-decidable#2»

/-- **Exercise `exer:regular-complete-mealy`** (a regular-complete language): `Transducers.lastLetterTrue_regularCompleteMealy`. -/
alias «exer:regular-complete-mealy» := Transducers.lastLetterTrue_regularCompleteMealy
assert_no_sorry «exer:regular-complete-mealy»

/-- **Exercise `exer:regular-complete-mealy-2`** (deciding regular-completeness): `Transducers.regularCompleteMealy_dfa_iff`. -/
alias «exer:regular-complete-mealy-2» := Transducers.regularCompleteMealy_dfa_iff
assert_no_sorry «exer:regular-complete-mealy-2»

/-- **Exercise `exer:regular-complete-mealy-2`** (deciding regular-completeness): `Transducers.decidableRegularCompleteMealy`. -/
alias «exer:regular-complete-mealy-2#2» := Transducers.decidableRegularCompleteMealy
assert_no_sorry «exer:regular-complete-mealy-2#2»

/-- **Exercise `exer:flip-flop-from-sequential-composition`** (flip-flops from two-state flip-flops): `Transducers.flipflop_twoState_decomposition`. -/
alias «exer:flip-flop-from-sequential-composition» := Transducers.flipflop_twoState_decomposition
assert_no_sorry «exer:flip-flop-from-sequential-composition»

/-- **Exercise `exer:delay-not-flip-flop-composition`** (the delay function): `Transducers.delay_not_reversible_composition`. -/
alias «exer:delay-not-flip-flop-composition» := Transducers.delay_not_reversible_composition
assert_no_sorry «exer:delay-not-flip-flop-composition»

/-- **Exercise `exer:alternating-not-flip-flop-composition`** (the alternating function): `Transducers.alternating_not_flipflop_composition`. -/
alias «exer:alternating-not-flip-flop-composition» := Transducers.alternating_not_flipflop_composition
assert_no_sorry «exer:alternating-not-flip-flop-composition»

/-- **Exercise `exer:invertible-mealy-is-reversible`** (invertible vs reversible): `Transducers.invertible_reversible_independent`. -/
alias «exer:invertible-mealy-is-reversible» := Transducers.invertible_reversible_independent
assert_no_sorry «exer:invertible-mealy-is-reversible»

/-- **Exercise `ex:map-lifting-continuous`** (continuity of the map lifting): `Transducers.mapLift_continuous_of_continuous`. -/
alias «ex:map-lifting-continuous» := Transducers.mapLift_continuous_of_continuous
assert_no_sorry «ex:map-lifting-continuous»


/-
The exercises that carry a `\label` in the sources, from `EXERCISES.md`.
Exercises are not numbered results of the main text; the ones with no label in
the sources are listed in `EXERCISES.md` by chapter and position instead, and
are not aliased here.
-/

/-- **Exercise `exer:reverse-continuous`** (continuity of reversal): `Transducers.Exercises.reverse_continuous`. -/
alias «exer:reverse-continuous» := Transducers.Exercises.reverse_continuous
assert_no_sorry «exer:reverse-continuous»

/-- **Exercise `exer:duplication-continuous`** (continuity of duplication): `Transducers.Exercises.duplication_continuous`. -/
alias «exer:duplication-continuous» := Transducers.Exercises.duplication_continuous
assert_no_sorry «exer:duplication-continuous»

/-- **Exercise `exer:squaring-continuous`** (continuity of squaring): `Transducers.Exercises.squaring_continuous`. -/
alias «exer:squaring-continuous» := Transducers.Exercises.squaring_continuous
assert_no_sorry «exer:squaring-continuous»

/-- **Exercise `exer:factorial-continuous`** (continuity of the factorial function): `Transducers.Exercises.factorial_continuous`. -/
alias «exer:factorial-continuous» := Transducers.Exercises.factorial_continuous
assert_no_sorry «exer:factorial-continuous»

/-- **Exercise `exer:factorial-power-continuous`** (continuity of `w ↦ w^{g(|w|)!}`): `Transducers.Exercises.factorial_power_continuous`. -/
alias «exer:factorial-power-continuous» := Transducers.Exercises.factorial_power_continuous
assert_no_sorry «exer:factorial-power-continuous»

/-- **Exercise `ex:continuity-for-finite-images`** (finitely many output values): `Transducers.Exercises.continuous_iff_regular_fibers`. -/
alias «ex:continuity-for-finite-images» := Transducers.Exercises.continuous_iff_regular_fibers
assert_no_sorry «ex:continuity-for-finite-images»

/-- **Exercise `exer:finite-images-assumption-necessary`** (the assumption is necessary): `Transducers.Exercises.exists_regular_fibers_not_continuous`. -/
alias «exer:finite-images-assumption-necessary» :=
  Transducers.Exercises.exists_regular_fibers_not_continuous
assert_no_sorry «exer:finite-images-assumption-necessary»

/-- **Exercise `exer:middle-letter-not-continuous`** (the middle letter function): `Transducers.Exercises.middleLetter_not_continuous`. -/
alias «exer:middle-letter-not-continuous» := Transducers.Exercises.middleLetter_not_continuous
assert_no_sorry «exer:middle-letter-not-continuous»

/-- **Exercise `ex:distance`** (the distance on strings): `Transducers.Exercises.strDist`. -/
alias «ex:distance» := Transducers.Exercises.strDist
assert_no_sorry «ex:distance»

/-- **Exercise `ex:distance`** (it is a distance): `Transducers.Exercises.strDist_isMetric`. -/
alias «ex:distance#2» := Transducers.Exercises.strDist_isMetric
assert_no_sorry «ex:distance#2»

/-- **Exercise `ex:distance`** (it is even an ultrametric): `Transducers.Exercises.strDist_ultrametric`. -/
alias «ex:distance#3» := Transducers.Exercises.strDist_ultrametric
assert_no_sorry «ex:distance#3»

/-- **Exercise `ex:distance`** (the resulting metric space): `Transducers.Exercises.strMetric`. -/
alias «ex:distance#4» := Transducers.Exercises.strMetric
assert_no_sorry «ex:distance#4»

/-- **Exercise `exer:all-functions-continuous-for-metric`** (all functions are continuous): `Transducers.Exercises.strDist_all_continuous`. -/
alias «exer:all-functions-continuous-for-metric» := Transducers.Exercises.strDist_all_continuous
assert_no_sorry «exer:all-functions-continuous-for-metric»

/-- **Exercise `exer:continuous-iff-uniformly-continuous`** (continuity is uniform continuity): `Transducers.Exercises.continuous_iff_uniformContinuous`. -/
alias «exer:continuous-iff-uniformly-continuous» :=
  Transducers.Exercises.continuous_iff_uniformContinuous
assert_no_sorry «exer:continuous-iff-uniformly-continuous»

/-- **Exercise `exer:regular-languages-for-rational-relations`** (the domain of a rational relation): `Transducers.Exercises.rationalRel_domain_isRegular`. -/
alias «exer:regular-languages-for-rational-relations» :=
  Transducers.Exercises.rationalRel_domain_isRegular
assert_no_sorry «exer:regular-languages-for-rational-relations»

/-- **Exercise `exer:regular-languages-for-rational-relations`** (the range of a rational relation): `Transducers.Exercises.rationalRel_range_isRegular`. -/
alias «exer:regular-languages-for-rational-relations#2» :=
  Transducers.Exercises.rationalRel_range_isRegular
assert_no_sorry «exer:regular-languages-for-rational-relations#2»

/-- **Exercise `exer:non-regular-languages-for-rational-relations`** (the inputs with at most one output need not form a regular language): `Transducers.Exercises.exists_rationalRel_atMostOneOutput_not_isRegular`. -/
alias «exer:non-regular-languages-for-rational-relations» :=
  Transducers.Exercises.exists_rationalRel_atMostOneOutput_not_isRegular
assert_no_sorry «exer:non-regular-languages-for-rational-relations»

/-- **Exercise `exer:rational-relations-not-closed-under-intersection`** (rational relations are not closed under intersection): `Transducers.Exercises.exists_rationalRel_inter_not_rationalRel`. -/
alias «exer:rational-relations-not-closed-under-intersection» :=
  Transducers.Exercises.exists_rationalRel_inter_not_rationalRel
assert_no_sorry «exer:rational-relations-not-closed-under-intersection»

/-- **Exercise `exer:rational-relations-intersection-undecidable`** (nonemptiness of the intersection is undecidable): `Transducers.Exercises.rationalRel_intersection_undecidable`. -/
alias «exer:rational-relations-intersection-undecidable» :=
  Transducers.Exercises.rationalRel_intersection_undecidable
assert_no_sorry «exer:rational-relations-intersection-undecidable»

/-- **Exercise `exer:rational-output-size`** (finitely many outputs = affine bound on the output length): `Transducers.Exercises.rationalRel_finiteOutputs_iff_affine`. -/
alias «exer:rational-output-size» := Transducers.Exercises.rationalRel_finiteOutputs_iff_affine
assert_no_sorry «exer:rational-output-size»

/-- **Exercise `ex:recognisable-relations`** (the recognisable subsets of `A* x B*` are the finite unions of products of regular languages): `Transducers.Exercises.isRecognisableRel_iff_finite_union`. -/
alias «ex:recognisable-relations» := Transducers.Exercises.isRecognisableRel_iff_finite_union
assert_no_sorry «ex:recognisable-relations»

/-- **Exercise `exer:examples-of-rational-fun`** (item (a), the input if its length is even): `Transducers.Exercises.isBimachine_isRationalFun_evenLength`. -/
alias «exer:examples-of-rational-fun» := Transducers.Exercises.isBimachine_isRationalFun_evenLength
assert_no_sorry «exer:examples-of-rational-fun»

/-- **Exercise `exer:examples-of-rational-fun`** (item (b), swap the first and the last letter): `Transducers.Exercises.isBimachine_isRationalFun_swapFirstLast`. -/
alias «exer:examples-of-rational-fun#2» :=
  Transducers.Exercises.isBimachine_isRationalFun_swapFirstLast
assert_no_sorry «exer:examples-of-rational-fun#2»

/-- **Exercise `exer:examples-of-rational-fun`** (item (c), the last `#` and what follows it): `Transducers.Exercises.isBimachine_isRationalFun_upToLastHash`. -/
alias «exer:examples-of-rational-fun#3» :=
  Transducers.Exercises.isBimachine_isRationalFun_upToLastHash
assert_no_sorry «exer:examples-of-rational-fun#3»

/-- **Exercise `exer:non-rational`** (item (a), the first half of the input): `Transducers.Exercises.not_isRationalFun_firstHalf`. -/
alias «exer:non-rational» := Transducers.Exercises.not_isRationalFun_firstHalf
assert_no_sorry «exer:non-rational»

/-- **Exercise `exer:non-rational`** (item (b), duplication): `Transducers.Exercises.not_isRationalFun_duplicate`. -/
alias «exer:non-rational#2» := Transducers.Exercises.not_isRationalFun_duplicate
assert_no_sorry «exer:non-rational#2»

/-- **Exercise `exer:decide-unambiguous`** (unambiguity of an nfa is decidable): `Transducers.Exercises.ambiguous_iff_reach`, the criterion of the solution. -/
alias «exer:decide-unambiguous» := Transducers.Exercises.ambiguous_iff_reach
assert_no_sorry «exer:decide-unambiguous»

/-- **Exercise `exer:decide-unambiguous`** (unambiguity of an nfa is decidable): `Transducers.Exercises.decidableUnambiguousNFA`. -/
alias «exer:decide-unambiguous#2» := Transducers.Exercises.decidableUnambiguousNFA
assert_no_sorry «exer:decide-unambiguous#2»

/-- **Exercise `exer:decide-rational-colision`** (item (a), the collision problem for two rational functions is undecidable): `Transducers.Exercises.rationalFun_collision_undecidable`. -/
alias «exer:decide-rational-colision» := Transducers.Exercises.rationalFun_collision_undecidable
assert_no_sorry «exer:decide-rational-colision»

/-- **Exercise `exer:rational-one-letter-input`** (the graph of a rational function over a one-letter input alphabet): `Transducers.Exercises.rationalFun_unary_graph`. -/
alias «exer:rational-one-letter-input» := Transducers.Exercises.rationalFun_unary_graph
assert_no_sorry «exer:rational-one-letter-input»

/-- **Exercise `exer:function-that-is-not-rational`** (not rational, yet rational after every rational function into a one-letter alphabet): `Transducers.Exercises.exists_not_isRationalFun_unary_compositions_rational`. -/
alias «exer:function-that-is-not-rational» :=
  Transducers.Exercises.exists_not_isRationalFun_unary_compositions_rational
assert_no_sorry «exer:function-that-is-not-rational»

/-- **Exercise `exer:some-ideals`** (first item, the functions with a range of size at most `k`): `Transducers.Exercises.isIdeal_rangeAtMost`. -/
alias «exer:some-ideals» := Transducers.Exercises.isIdeal_rangeAtMost
assert_no_sorry «exer:some-ideals»

/-- **Exercise `exer:some-ideals`** (second item, the functions with `O(n^k)` outputs): `Transducers.Exercises.isIdeal_outputsPoly`. -/
alias «exer:some-ideals#2» := Transducers.Exercises.isIdeal_outputsPoly
assert_no_sorry «exer:some-ideals#2»

/-- **Exercise `exer:finite-range-ideals`** (an ideal of functions with finite range is `RangeAtMost k` or `OutputsPoly 0`): `Transducers.Exercises.finite_range_ideal_classification`. -/
alias «exer:finite-range-ideals» := Transducers.Exercises.finite_range_ideal_classification
assert_no_sorry «exer:finite-range-ideals»

/-- **Exercise `exer:surjective-rational-function`** (a surjective rational function has a rational one-sided inverse): `Transducers.Exercises.exists_rationalFun_leftInverse`. -/
alias «exer:surjective-rational-function» := Transducers.Exercises.exists_rationalFun_leftInverse
assert_no_sorry «exer:surjective-rational-function»

/-- **Exercise `exer:two-letter-alphabet-suffices`** (a two-letter alphabet suffices for the prime regular functions): `Transducers.Exercises.isRegularFun_iff_compClosure2`. -/
alias «exer:two-letter-alphabet-suffices» := Transducers.Exercises.isRegularFun_iff_compClosure2
assert_no_sorry «exer:two-letter-alphabet-suffices»

/-- **Exercise `exer:mealy-as-restricted-mso-relabelling`** (Mealy machines are the restricted mso relabellings): `Transducers.Exercises.isMealy_iff_restrictedRelabelling`. -/
alias «exer:mealy-as-restricted-mso-relabelling» :=
  Transducers.Exercises.isMealy_iff_restrictedRelabelling
assert_no_sorry «exer:mealy-as-restricted-mso-relabelling»

/-- **Exercise `exer:simple-decomposition-example`** (the first-letter function as a composition of flip-flops): `Transducers.firstConst_flipflop_decomposition`. -/
alias «exer:simple-decomposition-example» := Transducers.firstConst_flipflop_decomposition
assert_no_sorry «exer:simple-decomposition-example»

/-- **Exercise `exer:simple-decomposition-example-2`** (the first-letter function is not a composition of reversible Mealy machines): `Transducers.firstConst_not_reversible_composition`. -/
alias «exer:simple-decomposition-example-2» := Transducers.firstConst_not_reversible_composition
assert_no_sorry «exer:simple-decomposition-example-2»

/-- **Exercise `exer:minimal-sequential`** (minimal sequential transducers are unique up to isomorphism): `Transducers.Exercises.minimal_sequential_unique`. -/
alias «exer:minimal-sequential» := Transducers.Exercises.minimal_sequential_unique
assert_no_sorry «exer:minimal-sequential»

/-- **Exercise `exer:minimal-subsequential`** (minimal subsequential transducers are not unique up to isomorphism): `Transducers.Exercises.minimal_subsequential_not_unique`. -/
alias «exer:minimal-subsequential» := Transducers.Exercises.minimal_subsequential_not_unique
assert_no_sorry «exer:minimal-subsequential»

/-- **Exercise `exer:non-minimal-bimachine`** (minimal bimachines are not unique up to isomorphism): `Transducers.Exercises.minimal_bimachine_not_unique`. -/
alias «exer:non-minimal-bimachine» := Transducers.Exercises.minimal_bimachine_not_unique
assert_no_sorry «exer:non-minimal-bimachine»

/-- **Exercise `exer:not-semiring-continuous`** (a regular function whose precomposition does not preserve the weighted-automaton functions): `Transducers.Exercises.exists_isRegularFun_not_weighted_precomp`. -/
alias «exer:not-semiring-continuous» :=
  Transducers.Exercises.exists_isRegularFun_not_weighted_precomp
assert_no_sorry «exer:not-semiring-continuous»

/-- **Exercise `exer:2dfa-boolean`** (the languages of deterministic two-way automata are closed under complement, union and intersection): `Transducers.Exercises.isTwoDFALang_boolean`. -/
alias «exer:2dfa-boolean» := Transducers.Exercises.isTwoDFALang_boolean
assert_no_sorry «exer:2dfa-boolean»

/-- **Exercise `exer:2dfa-loop-elimination`** (the set of inputs on which a deterministic two-way transducer terminates is a regular language): `Transducers.Exercises.halts_isRegular`. -/
alias «exer:2dfa-loop-elimination» := Transducers.Exercises.halts_isRegular
assert_no_sorry «exer:2dfa-loop-elimination»

/-- **Exercise `exer:sst-sorting`** (sorting the letters of a string is computed by an sst): `Transducers.Exercises.isSST_sort`. -/
alias «exer:sst-sorting» := Transducers.Exercises.isSST_sort
assert_no_sorry «exer:sst-sorting»

/-- **Exercise `exer:sst-copyful-sst`** (copyful ssts compute continuous functions): `Transducers.Exercises.continuous_of_isCopyfulSST`. -/
alias «exer:sst-copyful-sst» := Transducers.Exercises.continuous_of_isCopyfulSST
assert_no_sorry «exer:sst-copyful-sst»

/-- **Exercise `exer:sst-copyful-sst-output-size`** (the output of a copyful sst has at most exponential length, and this is attained): `Transducers.Exercises.CopyfulSST.output_length_exp_bound` and `Transducers.Exercises.exists_isCopyfulSST_exponential`. -/
alias «exer:sst-copyful-sst-output-size» :=
  Transducers.Exercises.CopyfulSST.output_length_exp_bound
assert_no_sorry «exer:sst-copyful-sst-output-size»

/-- **Exercise `exer:sst-copyful-sst-output-size`** (second item, an exponential example): `Transducers.Exercises.exists_isCopyfulSST_exponential`. -/
alias «exer:sst-copyful-sst-output-size#2» := Transducers.Exercises.exists_isCopyfulSST_exponential
assert_no_sorry «exer:sst-copyful-sst-output-size#2»

/-- **Exercise `exer:sst-copyful-sst-no-composition`** (the copyful sst functions are not closed under composition): `Transducers.Exercises.exists_isCopyfulSST_comp_not_isCopyfulSST`. -/
alias «exer:sst-copyful-sst-no-composition» :=
  Transducers.Exercises.exists_isCopyfulSST_comp_not_isCopyfulSST
assert_no_sorry «exer:sst-copyful-sst-no-composition»

/-- **Exercise `exer:sst-polynomial-automaton`** (a polynomial automaton computing `2^n`): `Transducers.Exercises.isPolyAut_two_pow`. -/
alias «exer:sst-polynomial-automaton» := Transducers.Exercises.isPolyAut_two_pow
assert_no_sorry «exer:sst-polynomial-automaton»

/-- **Exercise `exer:sst-polynomial-automaton-doubly-exponential`** (a polynomial automaton computing `2^{2^n}`): `Transducers.Exercises.isPolyAut_two_pow_two_pow`. -/
alias «exer:sst-polynomial-automaton-doubly-exponential» :=
  Transducers.Exercises.isPolyAut_two_pow_two_pow
assert_no_sorry «exer:sst-polynomial-automaton-doubly-exponential»

/-- **Exercise `exer:copyful-sst-decidable`** (equivalence of copyful ssts reduces to equivalence of polynomial automata): `Transducers.Exercises.copyfulSST_equivalence_reduces_to_polyAut`. -/
alias «exer:copyful-sst-decidable» :=
  Transducers.Exercises.copyfulSST_equivalence_reduces_to_polyAut
assert_no_sorry «exer:copyful-sst-decidable»

/-- **Exercise `exer:so-logic`** (second-order logic can define non-regular languages): `Transducers.Exercises.exists_SO_lang_not_isRegular`. -/
alias «exer:so-logic» := Transducers.Exercises.exists_SO_lang_not_isRegular
assert_no_sorry «exer:so-logic»

/-- **Exercise `exer:polyregular-marked-squaring-compression`** (marked squaring is not compatible with compression): `Transducers.Exercises.markedSquare_not_compatible_with_compression`. -/
alias «exer:polyregular-marked-squaring-compression» :=
  Transducers.Exercises.markedSquare_not_compatible_with_compression
assert_no_sorry «exer:polyregular-marked-squaring-compression»

/-- **Exercise `exer:2nft`** (first half: the first nondeterministic model of a two-way transducer is not contained in the second): `Transducers.Exercises.exists_isTwoNFT₁_not_isTwoNFT₂`. -/
alias «exer:2nft» := Transducers.Exercises.exists_isTwoNFT₁_not_isTwoNFT₂
assert_no_sorry «exer:2nft»

/-- **Exercise `exer:2nft`** (second half: the second nondeterministic model of a two-way transducer is not contained in the first): `Transducers.Exercises.exists_isTwoNFT₂_not_isTwoNFT₁`. -/
alias «exer:2nft#2» := Transducers.Exercises.exists_isTwoNFT₂_not_isTwoNFT₁
assert_no_sorry «exer:2nft#2»

/-- **Exercise `exer:for-transducers-simulate-fo`** (a first-order sentence is computed by a for-transducer of linear size): `Transducers.Exercises.exists_forProg_of_isFO`. -/
alias «exer:for-transducers-simulate-fo» := Transducers.Exercises.exists_forProg_of_isFO
assert_no_sorry «exer:for-transducers-simulate-fo»

/-
The theorem-like environments of the book that are not aliased
above, so that this file accounts for all of them:

* `def:rational-recognisable-subsets` (definition) -- not formalised (rational and recognisable subsets of a monoid, which the later sections do not use);
* `conj:regular-via-weighted-automata` (conjecture) -- a conjecture of the book, not a result to formalise;
* `nolabel:thm-fo-transduction-into-primes` (theorem) -- removed from the formalised theorems at the user's request; its statement is kept, commented out, in `PartC/MSOOpen.lean`;
-/

end Transducers.Book
